package br.sql.janelas.ponto;

import br.sql.acesso.SQLDatabaseConnection;
import br.sql.bean.FuncionariosPonto;
import br.sql.bean.JsysClientesIds;
import br.sql.util.ManagerData;
import br.sql.util.Progress;
import br.sql.util.Retorna;
import br.sql.util.timerKeys;
import java.awt.EventQueue;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingWorker;

/**
 *
 * @author Juliano Alves Medina
 */
public final class PontoJanela extends JPanel {

    private final timerKeys tk = new timerKeys();
    private static final SQLDatabaseConnection DADOS = new SQLDatabaseConnection();

    public PontoJanela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIdFuncionario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldEntrada1 = new javax.swing.JTextField();
        jTextFieldIntervalo = new javax.swing.JTextField();
        jTextFieldentrada2 = new javax.swing.JTextField();
        jTextFieldSaida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        FormListener formListener = new FormListener();

        setFocusable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFocusable(false);
        jPanel1.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Ponto");
        jLabel1.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(610, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(br.sql.util.ManagerData.getDataAtualTypeString());
        jLabel2.setFocusable(false);
        jLabel2.setRequestFocusEnabled(false);

        jTextFieldIdFuncionario.setDocument(new br.sql.plainDocument.IntegerDocument());
        jTextFieldIdFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldIdFuncionario.setFocusTraversalPolicyProvider(true);
        jTextFieldIdFuncionario.addKeyListener(formListener);

        jLabel3.setText("Colaborador");
        jLabel3.setFocusable(false);

        jTextFieldNome.setEditable(false);
        jTextFieldNome.setToolTipText("");
        jTextFieldNome.setFocusable(false);

        jTextFieldEntrada1.setEditable(false);
        jTextFieldEntrada1.setToolTipText("");
        jTextFieldEntrada1.setFocusable(false);

        jTextFieldIntervalo.setEditable(false);
        jTextFieldIntervalo.setToolTipText("");
        jTextFieldIntervalo.setFocusable(false);

        jTextFieldentrada2.setEditable(false);
        jTextFieldentrada2.setFocusable(false);

        jTextFieldSaida.setEditable(false);
        jTextFieldSaida.setFocusable(false);

        jLabel4.setText("Entrada");
        jLabel4.setFocusable(false);

        jLabel5.setText("Intervalo");
        jLabel5.setToolTipText("");
        jLabel5.setFocusable(false);

        jLabel6.setText("Entrada 2");
        jLabel6.setFocusable(false);

        jLabel7.setText("Saida");
        jLabel7.setFocusable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldIdFuncionario)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldEntrada1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIntervalo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldentrada2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIntervalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldentrada2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldIdFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.KeyListener {
        FormListener() {}
        public void keyPressed(java.awt.event.KeyEvent evt) {
            if (evt.getSource() == jTextFieldIdFuncionario) {
                PontoJanela.this.jTextFieldIdFuncionarioKeyPressed(evt);
            }
        }

        public void keyReleased(java.awt.event.KeyEvent evt) {
        }

        public void keyTyped(java.awt.event.KeyEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIdFuncionarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdFuncionarioKeyPressed
        tk.ativar();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (tk.isCartao() & !"".equals(jTextFieldIdFuncionario.getText().trim())) {
                final Progress p = new Progress();
                SwingWorker worker = new SwingWorker() {
                    @Override
                    protected Void doInBackground() throws Exception {
                        DADOS.execProcedure("registraPonto(" + jTextFieldIdFuncionario.getText().trim() + ")");
                        caregarPonto();
                        return null;
                    }

                    @Override
                    protected void done() {
                        super.done();
                        jTextFieldIdFuncionario.setText("");
                        p.dispose();
                    }

                    private void caregarPonto() {
                        Map<Object, Object> filtro = new HashMap<>();
                        filtro.put("id", jTextFieldIdFuncionario.getText().trim());
                        JsysClientesIds fun = (JsysClientesIds) Retorna.findOneResult("JsysClientesIds.findById", filtro);
                        if (fun != null) {
                            filtro.clear();
                            filtro.put("idFuncionario", fun.getJsysClientesIdsPK().getIdCliente());
                            filtro.put("inicio", ManagerData.getDataAtualTypeDate(ManagerData.INICIO));
                            filtro.put("fim", ManagerData.getDataAtualTypeDate(ManagerData.FIM));
                            FuncionariosPonto ponto = (FuncionariosPonto) Retorna.findOneResult("FuncionariosPonto.findByIdFuncionarioData", filtro);
                            if (ponto != null) {
                                jTextFieldNome.setText(ponto.getFuncionario().getNomeCorentista());
                                jTextFieldEntrada1.setText(ManagerData.convertDate(ponto.getEntrada(), "HH:mm:ss"));
                                jTextFieldIntervalo.setText(ManagerData.convertDate(ponto.getIntervaloInicio(), "HH:mm:ss"));
                                jTextFieldentrada2.setText(ManagerData.convertDate(ponto.getIntervaloFim(), "HH:mm:ss"));
                                jTextFieldSaida.setText(ManagerData.convertDate(ponto.getSaida(), "HH:mm:ss"));
                            } else {
                                jTextFieldNome.setText("Colaborador não encontrado.");
                                jTextFieldEntrada1.setText("00:00:00");
                                jTextFieldIntervalo.setText("00:00:00");
                                jTextFieldentrada2.setText("00:00:00");
                                jTextFieldSaida.setText("00:00:00");
                            }
                        }
                    }
                };
                worker.execute();
                p.setVisible(true);
            } else {
                jTextFieldIdFuncionario.setText("");
                tk.desativar();
                JOptionPane.showMessageDialog(null, "Passe novamente o cartão.");
            }
        }
    }//GEN-LAST:event_jTextFieldIdFuncionarioKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldEntrada1;
    private javax.swing.JTextField jTextFieldIdFuncionario;
    private javax.swing.JTextField jTextFieldIntervalo;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldSaida;
    private javax.swing.JTextField jTextFieldentrada2;
    // End of variables declaration//GEN-END:variables

    public static void main(final String[] args) {
        EventQueue.invokeLater(() -> {
            JFrame frame = new JFrame();
            frame.setContentPane(new PontoJanela());
            frame.pack();
            frame.setTitle("Controle de Ponto");
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    }
}
