package br.rel.filtros;

import br.sql.acesso.SQLDatabaseConnection;
import br.sql.bean.JsysTitulos;
import br.sql.log.Log;
import br.sql.util.ManagerData;
import br.sql.util.ReportUtils;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import jsys.sql.Menu;

/**
 *
 * @author Juliano Alves Medina
 */
public class FiltroDatasCaixa extends javax.swing.JDialog {
    
    private SQLDatabaseConnection dados = new SQLDatabaseConnection();

    /**
     * Creates new form FiltroDatasCaixa
     *
     * @param parent
     * @param modal
     */
    public FiltroDatasCaixa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dataInicialjDateChooser = new com.toedter.calendar.JDateChooser();
        dataFinaljDateChooser = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        titulosuJComboBox = new componentes.UJComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        caixasuJComboBox = new componentes.UJComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filtro Relatório");
        setResizable(false);

        jLabel1.setText("Data Inicial");
        jLabel1.setToolTipText("");

        jLabel2.setText("Data Final");

        jButton2.setText("Confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Caixa");
        jLabel3.setToolTipText("");

        jLabel4.setText("Titulos");
        jLabel4.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dataInicialjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dataFinaljDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(titulosuJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(caixasuJComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataInicialjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataFinaljDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(caixasuJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(titulosuJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Map<Object, Object> parametros = new HashMap<>();
        parametros.put("dataInicial", ManagerData.setHoraInicioDia(dataInicialjDateChooser.getDate()));
        parametros.put("dataFinal", ManagerData.setHoraFimDia(dataFinaljDateChooser.getDate()));
        parametros.put("titulo", titulosuJComboBox.getSelectedObject());
        parametros.put("caixa", caixasuJComboBox.getSelectedObject());
        ReportUtils.openReport("Relatorio", relatorio, parametros);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * deve ser um array com 4 posições 1 - caminho relatorio 2 - periodo dia
     * mes ... 3 - titulo 4 - codigo caixa
     *
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FiltroDatasCaixa dialog = new FiltroDatasCaixa(new javax.swing.JFrame(), false);
                dialog.setValores(args);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.UJComboBox caixasuJComboBox;
    private com.toedter.calendar.JDateChooser dataFinaljDateChooser;
    private com.toedter.calendar.JDateChooser dataInicialjDateChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private componentes.UJComboBox titulosuJComboBox;
    // End of variables declaration//GEN-END:variables

    private String relatorio;

    private void setValores(String[] args) {
        relatorio = args[0];
        String filtroData = args[1];
        if (filtroData.equals("DIA")) {
            dataInicialjDateChooser.setDate(ManagerData.setHoraInicioDia(ManagerData.getDate()));
            dataFinaljDateChooser.setDate(ManagerData.setHoraFimDia(ManagerData.getDate()));
        }
        if (filtroData.equals("MES")) {
            dataInicialjDateChooser.setDate(ManagerData.getPrimeiroDiaDoMes(ManagerData.getDate()));
            dataFinaljDateChooser.setDate(ManagerData.setHoraFimDia(ManagerData.getDate()));
        }
        if (filtroData.equals("ANO")) {
            dataInicialjDateChooser.setDate(ManagerData.getPrimeiroDiaDoAno(ManagerData.getDate()));
            dataFinaljDateChooser.setDate(ManagerData.setHoraFimDia(ManagerData.getDate()));
        }

        titulosuJComboBox.addItem("TODOS", "");
        for (Object O : br.sql.util.Retorna.findList("JsysTitulos.findAll")) {
            JsysTitulos t = (JsysTitulos) O;
            titulosuJComboBox.addItem(t.getIdTitulo(), t.getIdTitulo());
        }
        titulosuJComboBox.setSelectedIndex(0);

        try {
            caixasuJComboBox.addItem("TODOS - 0", "");
            ResultSet rs = dados.execSQL("SELECT DISTINCT jsysClientes.nomeCorentista, idBanco FROM JSYSRECEBER INNER JOIN jsysClientes ON IDBANCO = jsysClientes.idcliente ");
            while (rs.next()) {
                caixasuJComboBox.addItem(rs.getString(1) + " - " + rs.getString(2), rs.getString(2));
            }
        } catch (SQLException e) {
            Log.registraErro(this.getClass().getName(), "", e);
        }
        caixasuJComboBox.setSelectedItem(Menu.getNomeBanco() + " - " + Menu.getIdBanco());
        caixasuJComboBox.setEnabled(Menu.getUser().getIdGrupo().isGerencia());
    }
}
