/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.rel.filtros;

import br.sql.util.ReportUtils;
import java.util.HashMap;
import java.util.Map;
import br.sql.util.ManagerData;
import java.util.Date;

/**
 *
 * @author Juliano Alves Medina
 */
public final class FiltroDataInicialFinal extends javax.swing.JDialog {

    public static final int DIA = 0;
    public static final int MES = 1;
    public static final int ANO = 2;
    public static final int FIM_MES = 3;
    private Integer idVendedor;
    private String localRelatorio;

    /**
     * Creates new form ContasPagasFiltro
     *
     * @param parent ex: new javax.swing.JFrame()
     * @param modal se o formulario vai ser modal ou nao ex: true or false
     * @param localRelatorio local no CLASSPACH do relatorio ex:
     * "/br/rel/ponto/cartaoPonto.jasper"
     * @param periodo perito do filtro inicial ex: FiltroDataInicialFinal.MES
     * @param idVendedor codigo do vendedor
     */
    public FiltroDataInicialFinal(java.awt.Frame parent, boolean modal, String localRelatorio, int periodo, Integer idVendedor) {
        super(parent, modal);
        initComponents();
        setVariaveis(localRelatorio, periodo, idVendedor);
    }

    /**
     * Creates new form ContasPagasFiltro
     *
     * @param localRelatorio local no CLASSPACH do relatorio ex:
     * "/br/rel/ponto/cartaoPonto.jasper"
     * @param periodo perito do filtro inicial ex: FiltroDataInicialFinal.MES
     * @param idVendedor codigo do vendedor
     */
    public FiltroDataInicialFinal(String localRelatorio, int periodo, Integer idVendedor) {
        super(new javax.swing.JFrame(), false);
        initComponents();
        setVariaveis(localRelatorio, periodo, idVendedor);
    }

    /**
     * Creates new form ContasPagasFiltro
     *
     * @param localRelatorio local no CLASSPACH do relatorio ex:
     * "/br/rel/ponto/cartaoPonto.jasper"
     * @param periodo perito do filtro inicial ex: FiltroDataInicialFinal.MES
     */
    public FiltroDataInicialFinal(String localRelatorio, int periodo) {
        super(new javax.swing.JFrame(), false);
        initComponents();
        setVariaveis(localRelatorio, periodo, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        dataFinaljDateChooser = new com.toedter.calendar.JDateChooser();
        dataInicialjDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filtro Relatório");
        setResizable(false);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Data Inicial");
        jLabel1.setToolTipText("");

        jLabel2.setText("Data Final");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataInicialjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(dataFinaljDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataInicialjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataFinaljDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Map<Object, Object> parametros = new HashMap<>();
        parametros.put("dataInicial", ManagerData.setHoraInicioDia(dataInicialjDateChooser.getDate()));
        parametros.put("dataFinal", ManagerData.setHoraFimDia(dataFinaljDateChooser.getDate()));
        parametros.put("idVendedor", idVendedor);
        ReportUtils.openReport("Relatorio", localRelatorio, parametros);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dataFinaljDateChooser;
    private com.toedter.calendar.JDateChooser dataInicialjDateChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void setVariaveis(String localRelatorio, int periodo, Integer idVendedor) {
        this.localRelatorio = localRelatorio;
        switch (periodo) {
            case DIA:
                setdate(ManagerData.getDataAtualTypeDate(ManagerData.INICIO), ManagerData.getDataAtualTypeDate(ManagerData.FIM));
                break;
            case MES:
                setdate(ManagerData.getPrimeiroDiaDoMes(), ManagerData.getDataAtualTypeDate(ManagerData.FIM));
                break;
            case ANO:
                setdate(ManagerData.getPrimeiroDiaDoAno(ManagerData.getDate()), ManagerData.getDataAtualTypeDate(ManagerData.FIM));
                break;
            case FIM_MES:
                setdate(ManagerData.getPrimeiroDiaDoMes(), ManagerData.getUltimoDiaDoMes());
                break;
            default:
                setdate(ManagerData.getDataAtualTypeDate(ManagerData.INICIO), ManagerData.getDataAtualTypeDate(ManagerData.FIM));
                break;
        }
        this.idVendedor = idVendedor == null ? 0 : idVendedor;
    }

    private void setdate(Date dataInicial, Date dataFinal) {
        dataInicialjDateChooser.setDate(dataInicial);
        dataFinaljDateChooser.setDate(dataFinal);
    }
}
