package br.sql.janelas.pacote;

import br.sql.acesso.SQLDatabaseConnection;
import br.sql.log.Log;
import br.sql.util.Impressao;
import br.sql.util.Sons;
import br.sql.util.Validar;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juliano Alves Medina
 */
public class PacoteJanela extends javax.swing.JFrame {

    private final Sons sons;
    private static final SQLDatabaseConnection DADOS = new SQLDatabaseConnection();

    /**
     * Creates new form PacoteJanela
     */
    public PacoteJanela() {
        this.sons = new Sons();
        setTitle("Pacote");
        initComponents();
        new TaskLoadFichas().execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        mensagemPacote = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        idOrcamento = new javax.swing.JTextField();
        dataOrcamento = new javax.swing.JTextField();
        vendedorOrcamento = new javax.swing.JTextField();
        ClienteOrcamento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fichaOrcamento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        valorOrcamento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pagamentoOrcamento = new javax.swing.JTextField();
        fichaJtextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFichas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Pacote");
        jLabel1.setToolTipText("");
        jLabel1.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.setFocusable(false);

        jTableProdutos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableProdutos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTableProdutos.setFocusable(false);
        jTableProdutos.setRowHeight(24);
        jScrollPane1.setViewportView(jTableProdutos);

        mensagemPacote.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mensagemPacote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensagemPacote.setToolTipText("");
        mensagemPacote.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensagemPacote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensagemPacote, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );

        idOrcamento.setEditable(false);
        idOrcamento.setBackground(new java.awt.Color(153, 255, 153));
        idOrcamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dataOrcamento.setEditable(false);
        dataOrcamento.setBackground(new java.awt.Color(153, 255, 153));
        dataOrcamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dataOrcamento.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        vendedorOrcamento.setEditable(false);
        vendedorOrcamento.setBackground(new java.awt.Color(153, 255, 153));
        vendedorOrcamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        ClienteOrcamento.setEditable(false);
        ClienteOrcamento.setBackground(new java.awt.Color(153, 255, 153));
        ClienteOrcamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Codigo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Data");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Vendedor");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Cliente");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Ficha");
        jLabel6.setToolTipText("");

        fichaOrcamento.setEditable(false);
        fichaOrcamento.setBackground(new java.awt.Color(153, 255, 153));
        fichaOrcamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fichaOrcamento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fichaOrcamento.setToolTipText("");
        fichaOrcamento.setFocusable(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Valor");
        jLabel7.setToolTipText("");

        valorOrcamento.setEditable(false);
        valorOrcamento.setBackground(new java.awt.Color(153, 255, 153));
        valorOrcamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valorOrcamento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Forma Pagamento");
        jLabel8.setToolTipText("");

        pagamentoOrcamento.setEditable(false);
        pagamentoOrcamento.setBackground(new java.awt.Color(153, 255, 153));
        pagamentoOrcamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pagamentoOrcamento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pagamentoOrcamento.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagamentoOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fichaOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vendedorOrcamento))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClienteOrcamento)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(fichaOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vendedorOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(valorOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(pagamentoOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fichaJtextField.setDocument(new br.sql.plainDocument.IntegerDocument(10));
        fichaJtextField.setToolTipText("");
        fichaJtextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fichaJtextFieldKeyPressed(evt);
            }
        });

        jTableFichas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableFichas.setFocusable(false);
        jScrollPane2.setViewportView(jTableFichas);

        jButton1.setText("Atualizar");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Imprimir");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fichaJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fichaJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fichaJtextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fichaJtextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            new TaskVerificaFicha().execute();
            new TaskLoadFichas().execute();
        }
    }//GEN-LAST:event_fichaJtextFieldKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new TaskLoadFichas().execute();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            int[] selected = jTableFichas.getSelectedRows();
            for (int i = 0; i < selected.length; i++) {
                Impressao.vendaPaga(jTableFichas.getValueAt(selected[i], 0).toString());
            }
        } catch (Exception e) {
            Log.registraErro(this.getClass().getName(), "jButton2ActionPerformed", e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ClienteOrcamento;
    private javax.swing.JTextField dataOrcamento;
    private javax.swing.JTextField fichaJtextField;
    private javax.swing.JTextField fichaOrcamento;
    private javax.swing.JTextField idOrcamento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableFichas;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JLabel mensagemPacote;
    private javax.swing.JTextField pagamentoOrcamento;
    private javax.swing.JTextField valorOrcamento;
    private javax.swing.JTextField vendedorOrcamento;
    // End of variables declaration//GEN-END:variables

    private void setCores(Color Foreground, Color Background) {
        jPanel2.setBackground(Background);
        mensagemPacote.setForeground(Foreground);
    }

    private class TaskLoadFichas extends SwingWorker<Void, Void> {

        @Override
        protected Void doInBackground() {
            try {
                ResultSet x = DADOS.execSQL("SELECT jsysOrcamento.idOrcamento AS Codigo, jsysOrcamento.Ficha, vend.nomeCorentista AS Vendedor, convert(DECIMAL(16, 2), jsysOrcamento.valorLiquido) AS Valor FROM jsysOrcamento LEFT JOIN jsysClientes AS vend ON jsysOrcamento.idFuncionario = vend.idCliente WHERE (jsysOrcamento.cancelado = 0) AND (jsysOrcamento.vendido = 1) AND (jsysOrcamento.entregue = 1) AND (jsysOrcamento.data = dbo.setTimeNull(getdate())) ORDER BY jsysOrcamento.dataVendido DESC");
                String[] tableColumnsName = {"Código", "Ficha", "Vendedor", "Valor"};
                DefaultTableModel aModel = new DefaultTableModel() {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                };
                aModel.setColumnIdentifiers(tableColumnsName);
                java.sql.ResultSetMetaData rsmd = x.getMetaData();
                int colNo = rsmd.getColumnCount();
                while (x.next()) {
                    Object[] objects = new Object[colNo];
                    for (int i = 0; i < colNo; i++) {
                        objects[i] = x.getObject(i + 1);
                    }
                    aModel.addRow(objects);
                }
                jTableFichas.setModel(aModel);
                jTableFichas.setDefaultRenderer(Object.class, new br.sql.defaultTableCellRenderer.ZebradoLocation());
            } catch (Exception e) {
                Log.registraErro(this.getClass().getName(), "caregarFichas", e);
            }
            return null;
        }
    }

    private class TaskVerificaFicha extends SwingWorker<Void, String> {

        @Override
        protected Void doInBackground() {
            try {
                String ficha = fichaJtextField.getText().trim();
                fichaJtextField.setText("");
                if (Validar.isNotNullOrWhite(ficha)) {
                    StringBuilder sql = new StringBuilder();
                    sql.append("SELECT idOrcamento, ficha, data, vendedor, cliente, valorLiquido, Quitado, formaPagto ")
                            .append("FROM jsysPacotefichas ")
                            .append("WHERE ficha = ").append(ficha);
                    ResultSet jpf = DADOS.execSQL(sql.toString());
                    if (jpf.next()) {
                        Integer orcamento = jpf.getInt("idOrcamento");
                        idOrcamento.setText(String.valueOf(orcamento));
                        fichaOrcamento.setText(jpf.getString("ficha"));
                        dataOrcamento.setText(br.sql.util.ManagerData.convertBrDate(jpf.getDate("data")));
                        vendedorOrcamento.setText(jpf.getString("vendedor"));
                        ClienteOrcamento.setText(jpf.getString("cliente"));
                        pagamentoOrcamento.setText(jpf.getString("formaPagto"));
                        valorOrcamento.setText(br.sql.util.ManagerDecimal.converter(jpf.getBigDecimal("valorLiquido")));
                        if (jpf.getBoolean("Quitado")) {
                            setCores(Color.WHITE, Color.BLUE);
                            mensagemPacote.setText(new StringBuilder().append("A Ficha ").append(ficha).append(" está Paga").toString());
                            try {
                                StringBuilder sql2 = new StringBuilder();
                                sql2.append("select jsysOrcamentoItens.idProduto, jsysProdutosT.nomeProduto, CAST(jsysOrcamentoItens.quantidade as DECIMAL(22,0)), CAST(jsysOrcamentoItens.precoVenda as DECIMAL(22,2)) ")
                                        .append("from jsysOrcamentoItens inner join jsysProdutosT on jsysProdutosT.idProduto = jsysOrcamentoItens.idProduto ")
                                        .append("where (jsysOrcamentoItens.idOrcamento = ").append(orcamento).append(") ");
                                ResultSet x = DADOS.execSQL(sql2.toString());
                                String[] tableColumnsName = {"Codigo", "Nome do Produto", "Quantidade", "Valor Venda"};
                                DefaultTableModel aModel = new DefaultTableModel() {
                                    @Override
                                    public boolean isCellEditable(int row, int column) {
                                        return false;
                                    }
                                };
                                aModel.setColumnIdentifiers(tableColumnsName);

                                java.sql.ResultSetMetaData rsmd = x.getMetaData();
                                int colNo = rsmd.getColumnCount();
                                while (x.next()) {
                                    Object[] objects = new Object[colNo];
                                    for (int i = 0; i < colNo; i++) {
                                        objects[i] = x.getObject(i + 1);
                                    }
                                    aModel.addRow(objects);
                                }
                                jTableProdutos.setModel(aModel);
                                jTableProdutos.setDefaultRenderer(Object.class, new br.sql.defaultTableCellRenderer.ZebradoLocation());
                                jTableProdutos.getColumnModel().getColumn(1).setPreferredWidth(400);
                            } catch (SQLException e) {
                                Log.registraErro(this.getClass().getName(), "caregarProdutos", e);
                            }
                            DADOS.execProcedure("PacoteEntrega(" + String.valueOf(orcamento) + ")");
                            sons.pago();
                        } else {
                            setCores(Color.BLACK, Color.RED);
                            jTableProdutos.setModel(new DefaultTableModel());
                            mensagemPacote.setText(new StringBuilder().append("Verificar com o Caixa se a Ficha ").append(ficha).append(" já Foi Quitada !!!").toString());
                            sons.aPagar();
                        }
                    } else {
                        jTableProdutos.setModel(new DefaultTableModel());
                        setCores(Color.WHITE, Color.BLACK);
                        idOrcamento.setText("");
                        fichaOrcamento.setText("");
                        dataOrcamento.setText("");
                        vendedorOrcamento.setText("");
                        ClienteOrcamento.setText("");
                        pagamentoOrcamento.setText("");
                        valorOrcamento.setText("");
                        mensagemPacote.setText(new StringBuilder().append("Verificar com o Caixa se a Ficha ").append(ficha).append(" já Foi Quitada !!!").toString());
                        sons.naoEncontrado();
                    }
                } else {
                    mensagemPacote.setText("Passe novamente o cartão.");
                }
            } catch (Exception e) {
                Log.registraErro(this.getClass().getName(), "TaskVerificaFichado.InBackground", e);
            }
            return null;
        }
    }
}
