package br.sql.cadastros.produtos;

import br.sql.acesso.SQLDatabaseConnection;
import br.sql.bean.JsysLojas;
import br.sql.bean.JsysProdutosT;
import br.sql.bean.JsysProdutosTBarra;
import br.sql.bean.JsysProdutosTFabricantes;
import br.sql.bean.JsysProdutosTFamilias;
import br.sql.bean.JsysProdutosTGrupos;
import br.sql.bean.JsysProdutosTPrecos;
import br.sql.bean.JsysProdutosTTributacao;
import br.sql.bean.Ncm;
import br.sql.log.Log;
import br.sql.util.ManagerDecimal;
import br.sql.util.Retorna;
import br.sql.util.Sons;
import java.awt.AWTKeyStroke;
import java.awt.Color;
import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import javax.swing.AbstractCellEditor;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellEditor;
import jsys.sql.Menu;

/**
 *
 * @author Juliano Alves Medina
 */
public final class ProdutosEdit extends javax.swing.JDialog {

    private static final SQLDatabaseConnection DADOS = new SQLDatabaseConnection();
    private Integer idProduto = 0;
    private Sons sons = new Sons();

    /**
     *
     * @return o codigo do ultimo Produto
     */
    public Integer getIdProduto() {
        return idProduto;
    }

    private Integer erro = 0;
    private ProdutosJanela produtosJanela;

    /**
     * Creates new form ProdutosEdit
     *
     * @param parent
     * @param modal
     * @param p
     * @param aThis
     */
    @SuppressWarnings("unchecked")
    public ProdutosEdit(java.awt.Frame parent, boolean modal, JsysProdutosT p, ProdutosJanela aThis) {
        super(parent, false);
        setRegistroAtual(p);
        this.produtosJanela = aThis;
        if (RegistroAtual.getIdProduto() != 0) {
            setRegistroAtualPrecos(Retorna.jsysProdutoTPrecos(RegistroAtual.getIdProduto()));
        } else {
            List<JsysProdutosTPrecos> lp = new ArrayList<>();
            List<JsysLojas> l = Retorna.jsysLojas();
            for (JsysLojas j : l) {
                lp.add(new JsysProdutosTPrecos(RegistroAtual.getIdProduto(), j.getIdloja(), BigDecimal.ZERO));
            }
            setRegistroAtualPrecos(lp);
        }
        initComponents();
        jTablePrecos.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        caregaDados();
        HashSet conj = new HashSet(jPanel2.getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        jPanel2.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jsysProdutosTFamiliasQuery = java.beans.Beans.isDesignTime() ? null : br.sql.acesso.ConnectionFactory.getEntityManagerNew().createQuery("SELECT j FROM JsysProdutosTFamilias j");
        jsysProdutosTFamiliasList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(jsysProdutosTFamiliasQuery.getResultList());
        jsysProdutosTGruposQuery = java.beans.Beans.isDesignTime() ? null : br.sql.acesso.ConnectionFactory.getEntityManagerNew().createQuery("SELECT j FROM JsysProdutosTGrupos j");
        jsysProdutosTGruposList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(jsysProdutosTGruposQuery.getResultList());
        jsysProdutosTFabricantesQuery = java.beans.Beans.isDesignTime() ? null : br.sql.acesso.ConnectionFactory.getEntityManagerNew().createQuery("SELECT j FROM JsysProdutosTFabricantes j");
        jsysProdutosTFabricantesList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(jsysProdutosTFabricantesQuery.getResultList());
        queryAtualJsysProdutosTBarra = java.beans.Beans.isDesignTime() ? null : br.sql.acesso.ConnectionFactory.getEntityManagerNew().createQuery("SELECT j FROM JsysProdutosTBarra j WHERE j.jsysProdutosTBarraPK.idProduto = " + RegistroAtual.getIdProduto().toString());
        retistroAtualJsysProdutosTBarra = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryAtualJsysProdutosTBarra.getResultList());
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNomeProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMarca = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldRef = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelGeral = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jTextField20 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jTextField25 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        uJComboBoxFamilias = new componentes.UJComboBox();
        uJComboBoxGrupo = new componentes.UJComboBox();
        uJComboBoxFabricantes = new componentes.UJComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanelTributos = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        uJComboBoxOrigemFiscal = new componentes.UJComboBox();
        uJComboBoxIdTributacao = new componentes.UJComboBox();
        jLabel30 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextFieldNCM = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrecos = new javax.swing.JTable();
        jTextFieldCompra = new javax.swing.JTextField();
        jTextFieldFrete = new javax.swing.JTextField();
        jTextFieldEncargos = new javax.swing.JTextField();
        jTextFieldCusto = new javax.swing.JTextField();
        jTextFieldDespOper = new javax.swing.JTextField();
        jTextFieldMargenLucro = new javax.swing.JTextField();
        jTextFieldAgregado = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        addCodigoBarras = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableBarras = new javax.swing.JTable();
        erroCodBarra = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextFieldLocaliza = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro de Produto");
        jLabel1.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setToolTipText("");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${registroAtual.idProduto}"), jLabel3, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Descrição:");
        jLabel2.setToolTipText("");

        jTextFieldNomeProduto.setDocument(new br.sql.plainDocument.JTextFieldTamanhoMaxDocument(255));
        jTextFieldNomeProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNomeProduto.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Marca:");
        jLabel4.setToolTipText("");

        jTextFieldMarca.setDocument(new br.sql.plainDocument.JTextFieldTamanhoMaxDocument(50));
        jTextFieldMarca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldMarca.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Und Compra:");
        jLabel8.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Und Venda:");
        jLabel9.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Referência:");
        jLabel10.setToolTipText("");

        jTextFieldRef.setDocument(new br.sql.plainDocument.JTextFieldTamanhoMaxDocument(20));
        jTextFieldRef.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldRef.setToolTipText("");

        jLabel27.setText("Obs:");
        jLabel27.setToolTipText("");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${registroAtual.obs}"), jTextArea1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane2.setViewportView(jTextArea1);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario Inclusão"));

        jTextField20.setEditable(false);
        jTextField20.setBackground(new java.awt.Color(204, 255, 204));
        jTextField20.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jTextField20.setText(br.sql.util.ManagerData.convertDate(RegistroAtual.getDataInclusao(), "dd/MM/yyyy HH:mm:ss")
        );

        jTextField22.setEditable(false);
        jTextField22.setBackground(new java.awt.Color(204, 255, 204));
        jTextField22.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${registroAtual.usuarioInclusao}"), jTextField22, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField22, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario Alteração"));

        jTextField25.setEditable(false);
        jTextField25.setBackground(new java.awt.Color(204, 255, 204));
        jTextField25.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${registroAtual.usuarioAlteracao}"), jTextField25, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextField21.setEditable(false);
        jTextField21.setBackground(new java.awt.Color(204, 255, 204));
        jTextField21.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jTextField21.setText(br.sql.util.ManagerData.convertDate(RegistroAtual.getDataAlteracao(), "dd/MM/yyyy HH:mm:ss"));
        jTextField21.setToolTipText("");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Familía:");
        jLabel5.setToolTipText("");

        uJComboBoxFamilias.setEditable(true);
        uJComboBoxFamilias.setAutocompletar(true);

        uJComboBoxGrupo.setAutocompletar(true);

        uJComboBoxFabricantes.setAutocompletar(true);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Grupo:");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Fabricante:");
        jLabel7.setToolTipText("");

        jButton5.setText("...");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("...");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("...");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGeralLayout = new javax.swing.GroupLayout(jPanelGeral);
        jPanelGeral.setLayout(jPanelGeralLayout);
        jPanelGeralLayout.setHorizontalGroup(
            jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeralLayout.createSequentialGroup()
                .addGroup(jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGeralLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelGeralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanelGeralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelGeralLayout.createSequentialGroup()
                                .addComponent(uJComboBoxFamilias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5))
                            .addComponent(jLabel6)
                            .addGroup(jPanelGeralLayout.createSequentialGroup()
                                .addComponent(uJComboBoxGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6))
                            .addComponent(jLabel7)
                            .addGroup(jPanelGeralLayout.createSequentialGroup()
                                .addComponent(uJComboBoxFabricantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7)))
                        .addGap(6, 6, 6)))
                .addGap(12, 12, 12)
                .addGroup(jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGeralLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelGeralLayout.setVerticalGroup(
            jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGeralLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelGeralLayout.createSequentialGroup()
                        .addGroup(jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uJComboBoxFamilias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uJComboBoxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uJComboBoxFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Geral", null, jPanelGeral, "");

        jLabel21.setText("Origem Fiscal");
        jLabel21.setToolTipText("");

        jLabel22.setText("Situação Tributaria");
        jLabel22.setToolTipText("");

        jLabel30.setText("NCM");
        jLabel30.setToolTipText("");

        jButton3.setText("...");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextFieldNCM.setToolTipText("");

        javax.swing.GroupLayout jPanelTributosLayout = new javax.swing.GroupLayout(jPanelTributos);
        jPanelTributos.setLayout(jPanelTributosLayout);
        jPanelTributosLayout.setHorizontalGroup(
            jPanelTributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTributosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uJComboBoxOrigemFiscal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelTributosLayout.createSequentialGroup()
                        .addGroup(jPanelTributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTributosLayout.createSequentialGroup()
                                .addGroup(jPanelTributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jTextFieldNCM, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addComponent(jLabel22)
                            .addComponent(jLabel21))
                        .addGap(0, 686, Short.MAX_VALUE))
                    .addComponent(uJComboBoxIdTributacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTributosLayout.setVerticalGroup(
            jPanelTributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTributosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uJComboBoxOrigemFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTributosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(uJComboBoxIdTributacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jTextFieldNCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tributos", jPanelTributos);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Compra:");
        jLabel13.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Frete:");
        jLabel14.setToolTipText("");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Encargos:");
        jLabel15.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Custo:");
        jLabel16.setToolTipText("");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Des Oper:");
        jLabel17.setToolTipText("");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Margen Lucro:");
        jLabel18.setToolTipText("");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Agregado:");
        jLabel19.setToolTipText("");

        jTablePrecos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTablePrecos.setRowHeight(20);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${registroAtualPrecos}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTablePrecos);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${jsysProdutosTPrecosPK.idloja}"));
        columnBinding.setColumnName("Loja");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${precoVenda}"));
        columnBinding.setColumnName("Preço de Venda");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTablePrecos);
        if (jTablePrecos.getColumnModel().getColumnCount() > 0) {
            jTablePrecos.getColumnModel().getColumn(0).setCellRenderer(new ProdutosPrecosLojasCellRenderer());
            jTablePrecos.getColumnModel().getColumn(1).setCellEditor(new precoVendaTableCellEditor());
            jTablePrecos.getColumnModel().getColumn(1).setCellRenderer(new precoVendaCellRenderer());
        }

        jTextFieldCompra.setDocument(new br.sql.plainDocument.MoedaDocument());
        jTextFieldCompra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCompra.setToolTipText("");

        jTextFieldFrete.setDocument(new br.sql.plainDocument.MoedaDocument());
        jTextFieldFrete.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextFieldEncargos.setDocument(new br.sql.plainDocument.MoedaDocument());
        jTextFieldEncargos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextFieldCusto.setDocument(new br.sql.plainDocument.MoedaDocument());
        jTextFieldCusto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextFieldDespOper.setDocument(new br.sql.plainDocument.MoedaDocument());
        jTextFieldDespOper.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextFieldMargenLucro.setDocument(new br.sql.plainDocument.MoedaDocument());
        jTextFieldMargenLucro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextFieldAgregado.setDocument(new br.sql.plainDocument.MoedaDocument());
        jTextFieldAgregado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCompra)
                    .addComponent(jTextFieldFrete)
                    .addComponent(jTextFieldEncargos)
                    .addComponent(jTextFieldCusto)
                    .addComponent(jTextFieldDespOper)
                    .addComponent(jTextFieldMargenLucro)
                    .addComponent(jTextFieldAgregado, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(420, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextFieldFrete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextFieldEncargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextFieldCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextFieldDespOper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jTextFieldMargenLucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jTextFieldAgregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tabela de Preços", null, jPanel2, "");

        addCodigoBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addCodigoBarrasKeyPressed(evt);
            }
        });

        jLabel26.setText("Novo Codigo Barras:");
        jLabel26.setToolTipText("");

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, retistroAtualJsysProdutosTBarra, jTableBarras);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${jsysProdutosTBarraPK.idbarra}"));
        columnBinding.setColumnName("Barra");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane3.setViewportView(jTableBarras);

        erroCodBarra.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        erroCodBarra.setForeground(new java.awt.Color(204, 0, 0));
        erroCodBarra.setToolTipText("");

        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addComponent(addCodigoBarras))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(erroCodBarra, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(erroCodBarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Codigo de Barras", null, jPanel3, "");

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(204, 0, 0));
        jCheckBox1.setText("Desativado");
        jCheckBox1.setToolTipText("");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${registroAtual.inativo}"), jCheckBox1, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Estoque"));

        jTextField15.setEditable(false);
        jTextField15.setBackground(new java.awt.Color(255, 204, 204));
        jTextField15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField15.setToolTipText("");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${registroAtual.estoqueGeral}"), jTextField15, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextField16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField16.setToolTipText("");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${registroAtual.estMinimo}"), jTextField16, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextField17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField17.setToolTipText("");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${registroAtual.estMaximo}"), jTextField17, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Maximo:");
        jLabel24.setToolTipText("");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Minimo:");
        jLabel23.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Geral:");
        jLabel20.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField16, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(jTextField17)
                    .addComponent(jTextField15))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Peso:");
        jLabel28.setToolTipText("");

        jTextField23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField23.setToolTipText("");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${registroAtual.peso}"), jTextField23, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextField23.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField23FocusGained(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Localiza:");
        jLabel29.setToolTipText("");

        jTextFieldLocaliza.setDocument(new br.sql.plainDocument.JTextFieldTamanhoMaxDocument(50));
        jTextFieldLocaliza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldLocaliza.setToolTipText("");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UN", "CX", "PC", "KG", "M2", " " }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${registroAtual.unidadeCompra}"), jComboBox1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UN", "CX", "PC", "KG", "M2", " " }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${registroAtual.unidadeVenda}"), jComboBox2, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRef, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldLocaliza, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldNomeProduto)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(562, 562, 562)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldLocaliza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Tributos");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (produtosJanela != null) {
            produtosJanela.loadProdutos(idProduto.toString());
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            if (Salvar()) {
                this.dispose();
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Erro Inesperado...", "ERRO", JOptionPane.ERROR_MESSAGE);
            Log.registraErro(this.getClass().getName(), "jButton2ActionPerformed", e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addCodigoBarrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addCodigoBarrasKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Map<Object, Object> filtro = new HashMap<>();
            filtro.put("idProduto", idProduto);
            JsysProdutosT p = (JsysProdutosT) br.sql.util.Retorna.findOneResult("JsysProdutosT.findByIdProduto", filtro);
            if (p != null) {
                registraCodigoBarra();
            } else {
                if (Salvar()) {
                    registraCodigoBarra();
                }
            }
        }
    }//GEN-LAST:event_addCodigoBarrasKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        br.sql.buscas.ConsultaNcm ncm = new br.sql.buscas.ConsultaNcm(new javax.swing.JFrame(), true);
        ncm.setVisible(true);
        jTextFieldNCM.setText(ncm.getRetorno());
    }//GEN-LAST:event_jButton3ActionPerformed

    @SuppressWarnings("unchecked")
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Map<Object, Object> filtro = new HashMap<>();
        filtro.put("idbarra", jTableBarras.getValueAt(jTableBarras.getSelectedRow(), 0));
        JsysProdutosTBarra jpb = (JsysProdutosTBarra) br.sql.util.Retorna.findOneResult("JsysProdutosTBarra.findByIdbarra", filtro);
        br.sql.acesso.ConnectionFactory.delete(jpb);
        filtro.clear();
        filtro.put("idProduto", RegistroAtual.getIdProduto());
        retistroAtualJsysProdutosTBarra.clear();
        retistroAtualJsysProdutosTBarra.addAll(br.sql.util.Retorna.findCollection("JsysProdutosTBarra.findByIdProduto", filtro));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JFrame frame = new JFrame();
        frame.setContentPane(new FamiliasJanela(this));
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setTitle("Cadastro de Famílias");
        frame.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JFrame frame = new JFrame();
        frame.setContentPane(new GruposJanela(this));
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setTitle("Cadastro de Grupos");
        frame.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JFrame frame = new JFrame();
        frame.setContentPane(new FabricantesJanela(this));
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setTitle("Cadastro de Fabricantes");
        frame.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField23FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField23FocusGained
         jTextField23.selectAll();
    }//GEN-LAST:event_jTextField23FocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addCodigoBarras;
    private javax.swing.JLabel erroCodBarra;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelGeral;
    private javax.swing.JPanel jPanelTributos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableBarras;
    private javax.swing.JTable jTablePrecos;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextFieldAgregado;
    private javax.swing.JTextField jTextFieldCompra;
    private javax.swing.JTextField jTextFieldCusto;
    private javax.swing.JTextField jTextFieldDespOper;
    private javax.swing.JTextField jTextFieldEncargos;
    private javax.swing.JTextField jTextFieldFrete;
    private javax.swing.JTextField jTextFieldLocaliza;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldMargenLucro;
    private javax.swing.JTextField jTextFieldNCM;
    private javax.swing.JTextField jTextFieldNomeProduto;
    private javax.swing.JTextField jTextFieldRef;
    private java.util.List<br.sql.bean.JsysProdutosTFabricantes> jsysProdutosTFabricantesList;
    private javax.persistence.Query jsysProdutosTFabricantesQuery;
    private java.util.List<br.sql.bean.JsysProdutosTFamilias> jsysProdutosTFamiliasList;
    private javax.persistence.Query jsysProdutosTFamiliasQuery;
    private java.util.List<br.sql.bean.JsysProdutosTGrupos> jsysProdutosTGruposList;
    private javax.persistence.Query jsysProdutosTGruposQuery;
    private javax.persistence.Query queryAtualJsysProdutosTBarra;
    private java.util.List<br.sql.bean.JsysProdutosTBarra> retistroAtualJsysProdutosTBarra;
    private componentes.UJComboBox uJComboBoxFabricantes;
    private componentes.UJComboBox uJComboBoxFamilias;
    private componentes.UJComboBox uJComboBoxGrupo;
    private componentes.UJComboBox uJComboBoxIdTributacao;
    private componentes.UJComboBox uJComboBoxOrigemFiscal;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    JsysProdutosT RegistroAtual;

    /**
     * Get the value of RegistroAtual
     *
     * @return the value of RegistroAtual
     */
    public JsysProdutosT getRegistroAtual() {
        return RegistroAtual;
    }

    /**
     * Set the value of RegistroAtual
     *
     * @param RegistroAtual new value of RegistroAtual
     */
    public void setRegistroAtual(JsysProdutosT RegistroAtual) {
        this.RegistroAtual = RegistroAtual;
        idProduto = RegistroAtual.getIdProduto();
    }

    private transient final PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);

    /**
     * Add PropertyChangeListener.
     *
     * @param listener
     */
    @Override
    public void addPropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.addPropertyChangeListener(listener);
    }

    /**
     * Remove PropertyChangeListener.
     *
     * @param listener
     */
    @Override
    public void removePropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.removePropertyChangeListener(listener);
    }

    private List<JsysProdutosTPrecos> registroAtualPrecos;

    public List<JsysProdutosTPrecos> getRegistroAtualPrecos() {
        return registroAtualPrecos;
    }

    public void setRegistroAtualPrecos(List<JsysProdutosTPrecos> registroAtualPrecos) {
        this.registroAtualPrecos = registroAtualPrecos;
    }

    private void caregaDados() {
        loadTributos();
        loadFamilias();
        loadGrupos();
        loadFabricantes();
        List<OrigemFiscal> oFiscal = new ArrayList<>();
        oFiscal.add(new OrigemFiscal("0", "Nacional, exceto as indicadas nos códigos 3 a 5;"));
        oFiscal.add(new OrigemFiscal("1", "Estrangeira - Importação direta, exceto a indicada no código 6"));
        oFiscal.add(new OrigemFiscal("2", "Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7"));
        oFiscal.add(new OrigemFiscal("3", "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40%"));
        oFiscal.add(new OrigemFiscal("4", "Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos"));
        oFiscal.add(new OrigemFiscal("5", "Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40%"));
        oFiscal.add(new OrigemFiscal("6", "Estrangeira - Importação direta, sem similar nacional"));
        oFiscal.add(new OrigemFiscal("7", "Estrangeira - Adquirida no mercado interno, sem similar nacional"));
        for (OrigemFiscal o : oFiscal) {
            uJComboBoxOrigemFiscal.addItem(o.getId() + " - " + o.getOrigemFiscal(), o);
        }
        jTextFieldNomeProduto.setText(RegistroAtual.getNomeProduto().toUpperCase());
        jTextFieldMarca.setText(RegistroAtual.getMarca().toUpperCase());
        jTextFieldRef.setText(RegistroAtual.getReferencia().toUpperCase());
        jTextFieldLocaliza.setText(RegistroAtual.getProdLocaliza().toUpperCase());
        jTextFieldNCM.setText(RegistroAtual.getNCM());
        jTextFieldCompra.setText(ManagerDecimal.converter(RegistroAtual.getPrecoCompra(), "#,##0.00"));
        jTextFieldAgregado.setText(ManagerDecimal.converter(RegistroAtual.getPrecoAgregado(), "#,##0.00"));
        jTextFieldCusto.setText(ManagerDecimal.converter(RegistroAtual.getPrecoCusto(), "#,##0.00"));
        jTextFieldDespOper.setText(ManagerDecimal.converter(RegistroAtual.getPrecoDespesasOperacional(), "#,##0.00"));
        jTextFieldEncargos.setText(ManagerDecimal.converter(RegistroAtual.getPrecoEncargos(), "#,##0.00"));
        jTextFieldFrete.setText(ManagerDecimal.converter(RegistroAtual.getPrecoFrete(), "#,##0.00"));
        jTextFieldMargenLucro.setText(ManagerDecimal.converter(RegistroAtual.getMargemLucro(), "#,##0.00"));
    }

    private void loadTributos() {
        java.util.Collection listTributos = Retorna.findCollection("JsysProdutosTTributacao.findAll");
        for (Object o : listTributos) {
            JsysProdutosTTributacao t = (JsysProdutosTTributacao) o;
            uJComboBoxIdTributacao.addItem(t.getNome() + " - " + t.getDecreto(), t);
        }
        if (RegistroAtual.getIdTributacao() != null) {
            uJComboBoxIdTributacao.setSelectedItem(RegistroAtual.getIdTributacao().getNome() + " - " + RegistroAtual.getIdTributacao().getDecreto());
        }
    }

    @SuppressWarnings("unchecked")
    public void loadFabricantes() {
        // carega registros das Fabricantes
        try {
            br.sql.acesso.ConnectionFactory.iniciaBean();
            java.util.Collection data = jsysProdutosTFabricantesQuery.getResultList();
            for (Object entity : data) {
                br.sql.acesso.ConnectionFactory.getEntityManagerNew().refresh(entity);
            }
            jsysProdutosTFabricantesList.clear();
            jsysProdutosTFabricantesList.addAll(data);
            uJComboBoxFabricantes.clear();
            for (JsysProdutosTFabricantes fa : jsysProdutosTFabricantesList) {
                uJComboBoxFabricantes.addItem(fa.getNomefabricante(), fa);
            }
            uJComboBoxFabricantes.setSelectedItem(RegistroAtual.getIdFabricante().getNomefabricante());
        } catch (Exception e) {
            Log.registraErro(ProdutosEdit.class, "loadFabricantes", e);
        }
    }

    @SuppressWarnings("unchecked")
    public void loadGrupos() {
        // carega registros das Grupo
        try {
            br.sql.acesso.ConnectionFactory.iniciaBean();
            java.util.Collection data = jsysProdutosTGruposQuery.getResultList();
            for (Object entity : data) {
                br.sql.acesso.ConnectionFactory.getEntityManagerNew().refresh(entity);
            }
            jsysProdutosTGruposList.clear();
            jsysProdutosTGruposList.addAll(data);
            uJComboBoxGrupo.clear();
            for (JsysProdutosTGrupos g : jsysProdutosTGruposList) {
                uJComboBoxGrupo.addItem(g.getNomeGrupo(), g);
            }
            uJComboBoxGrupo.setSelectedItem(RegistroAtual.getIdGrupo().getNomeGrupo());
        } catch (Exception e) {
            Log.registraErro(ProdutosEdit.class, "loadGrupos", e);
        }
    }

    @SuppressWarnings("unchecked")
    public void loadFamilias() {
        // carega registros das Familias
        try {
            br.sql.acesso.ConnectionFactory.iniciaBean();
            java.util.Collection data = jsysProdutosTFamiliasQuery.getResultList();
            for (Object entity : data) {
                br.sql.acesso.ConnectionFactory.getEntityManagerNew().refresh(entity);
            }
            jsysProdutosTFamiliasList.clear();
            jsysProdutosTFamiliasList.addAll(data);

            uJComboBoxFamilias.clear();
            for (JsysProdutosTFamilias f : jsysProdutosTFamiliasList) {
                uJComboBoxFamilias.addItem(f.getNomeFamilia(), f);
            }
            uJComboBoxFamilias.setSelectedItem(RegistroAtual.getIdFamilia().getNomeFamilia());
        } catch (Exception e) {
            Log.registraErro(ProdutosEdit.class, "loadFamilias", e);
        }
    }

    /**
     * @return JsysProdutosTFamilias selecionado
     */
    private JsysProdutosTFamilias getuJComboBoxFamilias() {
        try {
            if (uJComboBoxFamilias.getSelectedItem() != null) {
                return (JsysProdutosTFamilias) uJComboBoxFamilias.getSelectedObject();
            } else {
                return new JsysProdutosTFamilias();
            }
        } catch (Exception e) {
            return new JsysProdutosTFamilias();
        }
    }

    /**
     * @return JsysProdutosTGrupos selecionado
     */
    private JsysProdutosTGrupos getuJComboBoxGrupo() {
        try {
            if (uJComboBoxGrupo.getSelectedItem() != null) {
                return (JsysProdutosTGrupos) uJComboBoxGrupo.getSelectedObject();
            } else {
                return new JsysProdutosTGrupos();
            }
        } catch (Exception e) {
            return new JsysProdutosTGrupos();
        }
    }

    /**
     * @return JsysProdutosTFabricantes selecionado
     */
    private JsysProdutosTFabricantes getuJComboBoxFabricantes() {
        try {
            if (uJComboBoxFabricantes.getSelectedItem() != null) {
                return (JsysProdutosTFabricantes) uJComboBoxFabricantes.getSelectedObject();
            } else {
                return new JsysProdutosTFabricantes();
            }
        } catch (Exception e) {
            return new JsysProdutosTFabricantes();
        }
    }

    private boolean validaCampos() {
        Map<Object, Object> filtro = new HashMap<>();
        filtro.put("codigo", jTextFieldNCM.getText());
        Ncm ncm = (Ncm) Retorna.findOneResult("Ncm.findByCodigo", filtro);
        if (ncm == null) {
            erro("Ncm Invalido ");
            jTabbedPane1.setSelectedComponent(this.jPanelTributos);
            jTextFieldNCM.requestFocus();
            return false;
        } else if (jTextFieldNomeProduto.getText().trim().equals("")) {
            erro("Nome do Produto Invalido ");
            jTextFieldNomeProduto.requestFocus();
            return false;
        } else if (getuJComboBoxFamilias().getIdFamilia() == null) {
            erro("Selecione uma Familia ");
            jTabbedPane1.setSelectedComponent(this.jPanelGeral);
            uJComboBoxFamilias.requestFocus();
            return false;
        } else if (getuJComboBoxGrupo().getIdGrupo() == null) {
            erro("Selecione um Grupo ");
            jTabbedPane1.setSelectedComponent(this.jPanelGeral);
            uJComboBoxGrupo.requestFocus();
            return false;
        } else if (getuJComboBoxFabricantes().getIdFabricante() == null) {
            erro("Selecione um Fabricante ");
            jTabbedPane1.setSelectedComponent(this.jPanelGeral);
            uJComboBoxFabricantes.requestFocus();
            return false;
        } else if (jTextFieldMarca.getText().equals("")) {
            erro("Marca Não pode Ficar em Branco ");
            jTextFieldMarca.requestFocus();
            return false;
        } else if (jTextFieldRef.getText().equals("")) {
            erro("Referencia Não pode Ficar em Branco ");
            jTextFieldRef.requestFocus();
            return false;
        } else if (jTextFieldLocaliza.getText().equals("")) {
            erro("Localiza Não pode Ficar em Branco ");
            jTextFieldLocaliza.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    /**
     * alterar isso aqui logo logo
     *
     * @return
     * @throws HeadlessException
     */
    private Boolean Salvar() throws HeadlessException {
        if (validaCampos()) {
            try {
                StringBuilder procProduto = new StringBuilder();
                procProduto.append("LancaProduto(")
                        .append(" ").append(RegistroAtual.getIdProduto()) // @idProduto
                        .append(", '").append(jTextFieldNomeProduto.getText().trim()) // @nomeProduto
                        .append("', '").append(jTextFieldNomeProduto.getText().trim()) // @principioAtivo
                        .append("', ").append(getuJComboBoxFamilias().getIdFamilia())//RegistroAtual.getIdFamilia().getIdFamilia()) // @idFamilia
                        .append(", ").append(getuJComboBoxGrupo().getIdGrupo()) // @idGrupo
                        .append(", ").append(getuJComboBoxFabricantes().getIdFabricante()) // @idFabricante
                        .append(", '").append(jTextFieldMarca.getText()) // @marca
                        .append("', '").append(RegistroAtual.getUnidadeCompra()) // @unidadeCompra
                        .append("', '").append(RegistroAtual.getUnidadeVenda()) // @unidadeVenda
                        .append("', '").append(jTextFieldRef.getText()) // @referencia
                        .append("', '").append(((OrigemFiscal) uJComboBoxOrigemFiscal.getSelectedObject()).getId()) // @origemFiscal
                        .append("', '10")
                        //.append("', '").append(((tipoICMS) uJComboBoxIdTributacao.getSelectedObject()).getId()) // @tipoIcms
                        .append("', ").append(RegistroAtual.getIcmsEstadual()) // @icmsEstadual
                        .append(", ").append(RegistroAtual.getIcmsInterestadual())//  @icmsInterestadual
                        .append(", '").append(RegistroAtual.getCfopEstadual())//  @cfopEstadual
                        .append("', '").append(RegistroAtual.getCfopInterestadual())//  @cfopInterestadual
                        .append("', ").append(ManagerDecimal.StringToBigDecimal(jTextFieldCompra.getText()))//  @precoCompra
                        .append(", ").append(ManagerDecimal.StringToBigDecimal(jTextFieldFrete.getText()))//  @precoFrete
                        .append(", ").append(ManagerDecimal.StringToBigDecimal(jTextFieldEncargos.getText()))//  @precoEncargos
                        .append(", ").append(ManagerDecimal.StringToBigDecimal(jTextFieldCusto.getText()))//  @precoCusto
                        .append(", ").append(RegistroAtual.getPrecoIpi())//  @precoIpi
                        .append(", ").append(RegistroAtual.getPrecoCreditoIcms())//  @precoCreditoIcms
                        .append(", ").append(RegistroAtual.getPrecoDebitoIcms())//  @precoDebitoIcms
                        .append(", ").append(RegistroAtual.getPrecoOutrosImpostos())//  @precoOutrosImpostos
                        .append(", ").append(RegistroAtual.getPrecoComissao())//  @precoComissao
                        .append(", ").append(ManagerDecimal.StringToBigDecimal(jTextFieldDespOper.getText()))//  @precoDespesasOperacional
                        .append(", ").append(ManagerDecimal.StringToBigDecimal(jTextFieldAgregado.getText()))//  @precoAgregado
                        .append(", ").append(ManagerDecimal.StringToBigDecimal(jTextFieldMargenLucro.getText()))//  @margemLucro
                        .append(", ").append(RegistroAtual.getEstMinimo())//  @estMinimo
                        .append(", ").append(RegistroAtual.getEstMaximo())//  @estMaximo
                        .append(", '").append(RegistroAtual.getAliquotaCupom())//  @aliquotaCupom
                        .append("', '").append(RegistroAtual.getAliquotaFora())//  @aliquotaFora
                        .append("', '").append(RegistroAtual.getObs())//  @obs
                        .append("', ").append(RegistroAtual.getInativo())//  @inativo
                        .append(", '").append(Menu.getNomeBanco())//  @usuario
                        .append("', ").append(RegistroAtual.getPeso())//  @peso
                        .append(", '").append(jTextFieldLocaliza.getText())//  @prodLocaliza
                        .append("', ").append(RegistroAtual.getComissaoVista())//  @comissaoVista
                        .append(", ").append(RegistroAtual.getComissaoPrazo()) //  @comissaoPrazo
                        .append(", '").append(jTextFieldNCM.getText()) //  @idNCM
                        .append("', '").append(RegistroAtual.getModBC()) //  @modBC
                        .append("', '").append(RegistroAtual.getModBCST()) //  @modBCST
                        .append("', '").append(RegistroAtual.getPisCST()) //  @pisCST
                        .append("', '").append(RegistroAtual.getCofinsCST()) //  @cofinsCST
                        .append("', '").append(RegistroAtual.getIpiCST()) //  @ipiCST
                        .append("', '").append(RegistroAtual.getTipoItem())
                        .append("', ").append(((JsysProdutosTTributacao) uJComboBoxIdTributacao.getSelectedObject()).getIdTributacao().toString())
                        .append(")");
                idProduto = DADOS.execProcudureRetInt(procProduto.toString());
                for (JsysProdutosTPrecos v : registroAtualPrecos) {
                    StringBuilder procPreco = new StringBuilder();
                    procPreco.append("LancaProdutoPreco(").append(idProduto)
                            .append(", '").append(v.getJsysProdutosTPrecosPK().getIdloja())
                            .append("', ").append(v.getPrecoVenda()).append(")");
                    erro += DADOS.execProcudureRetInt(procPreco.toString());
                }
                if (idProduto != -1 | erro == 0) {
                    jLabel3.setText(idProduto.toString());
                    JOptionPane.showMessageDialog(null, "Produto " + idProduto.toString() + " salvo com Sucesso", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
                    if (produtosJanela != null) {
                        produtosJanela.loadProdutos(idProduto.toString());
                    }
                    return true;
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao Salvar o Produto!!!", "Erro", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            } catch (Exception e) {
                Log.registraErro(getClass().getName(), "Salvar", e);
            }
        }
        return false;
    }

    private void erro(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem, "Erro", JOptionPane.ERROR_MESSAGE);
    }

    private void registraCodigoBarra() {
        erroCodBarra.setText("");
        try {
            String codBarra = addCodigoBarras.getText().trim();
            if (!codBarra.equals("")) {
                Map<Object, Object> filtro = new HashMap<>();
                filtro.put("idbarra", codBarra);
                JsysProdutosTBarra B = (JsysProdutosTBarra) br.sql.util.Retorna.findOneResult("JsysProdutosTBarra.findByIdbarra", filtro);
                if (B == null) {
                    JsysProdutosTBarra b = new JsysProdutosTBarra(codBarra, idProduto);
                    br.sql.acesso.ConnectionFactory.insert(b);
                    retistroAtualJsysProdutosTBarra.add(b);
                    sons.pago();
                } else {
                    if (Objects.equals(B.getJsysProdutosT().getIdProduto(), idProduto)) {
                        sons.pago();
                        erroCodBarra.setForeground(Color.blue);
                    } else {
                        sons.naoEncontrado();
                        erroCodBarra.setForeground(Color.red);
                    }
                    // erroCodBarra.setForeground(Objects.equals(B.getJsysProdutosT().getIdProduto(), idProduto) ? Color.blue : Color.red);
                    erroCodBarra.setText("já Cadastrado: " + B.getJsysProdutosT().getIdProduto().toString() + " - " + B.getJsysProdutosT().getNomeProduto());
                }
            }
        } catch (Exception e) {
            br.sql.log.Log.registraErro(this.getClass().getName(), "registraCodigoBarra", e);
        } finally {
            int row = retistroAtualJsysProdutosTBarra.size() - 1;
            jTableBarras.setRowSelectionInterval(row, row);
            jTableBarras.scrollRectToVisible(jTableBarras.getCellRect(row, 0, true));
            addCodigoBarras.setText("");
            addCodigoBarras.requestFocus();
        }
    }
}

class OrigemFiscal {

    private final String id;
    private final String origemFiscal;

    public OrigemFiscal(String id, String origemFiscal) {
        this.id = id;
        this.origemFiscal = origemFiscal;
    }

    public String getId() {
        return id;
    }

    public String getOrigemFiscal() {
        return origemFiscal;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final OrigemFiscal other = (OrigemFiscal) obj;
        return Objects.equals(this.id, other.id);
    }
}

class ProdutosPrecosLojasCellRenderer extends DefaultTableCellRenderer {

    @Override
    public Component getTableCellRendererComponent(JTable table,
            Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        setText(Retorna.jsysLojas(value.toString()).getNomeLoja());
        return this;
    }
}

class precoVendaTableCellEditor extends AbstractCellEditor implements TableCellEditor {

    private JTextField field;

    @Override
    public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
        field = new JTextField();
        field.setDocument(new br.sql.plainDocument.MoedaDocument());
        field.setBackground(new java.awt.Color(255, 204, 204));
        field.setFont(new java.awt.Font("Tahoma", 1, 16));
        field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        field.setText(value.toString().replaceAll("\\.", ""));
        field.selectAll();
        return field;
    }

    @Override
    public Object getCellEditorValue() {
        return (new BigDecimal(ManagerDecimal.StringToDouble(field.getText())));
    }
}

class precoVendaCellRenderer extends DefaultTableCellRenderer {

    @Override
    public Component getTableCellRendererComponent(JTable table,
            Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        setForeground(Color.black);
        setBackground(new java.awt.Color(204, 255, 204));
        setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        setFont(new java.awt.Font("Tahoma", 1, 16));
        setText(ManagerDecimal.converter((BigDecimal) value));
        return this;
    }
}
