/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * calculadora.java
 *
 * Created on 28/07/2011, 17:11:50
 */
package br.sql.util;

import java.awt.event.KeyEvent;

/**
 *
 * @author Juliano Alves Medina
 */
public class Calculadora extends javax.swing.JFrame {

    char aoperacao;
    String temp, numeroant, copia;
    double num1 = 0, num2 = 0, resultado = 0;

    /**
     * Creates new form calculadora
     */
    public Calculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private void escolheOperacao(char op) throws NumberFormatException {
        aoperacao = op;
        num1 = Double.parseDouble(JTVisor.getText());
        JTVisor.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JTVisor = new javax.swing.JTextField();
        JBBac = new javax.swing.JButton();
        JB7 = new javax.swing.JButton();
        JB4 = new javax.swing.JButton();
        JB1 = new javax.swing.JButton();
        JB0 = new javax.swing.JButton();
        JBCe = new javax.swing.JButton();
        JBCtr = new javax.swing.JButton();
        JBMaisMenos = new javax.swing.JButton();
        JBDivisao = new javax.swing.JButton();
        JBVeses = new javax.swing.JButton();
        JBMenos = new javax.swing.JButton();
        JBSoma = new javax.swing.JButton();
        JBIgual = new javax.swing.JButton();
        JB3 = new javax.swing.JButton();
        JB6 = new javax.swing.JButton();
        JB9 = new javax.swing.JButton();
        JB8 = new javax.swing.JButton();
        JB5 = new javax.swing.JButton();
        JB2 = new javax.swing.JButton();
        JBPonto = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);

        JTVisor.setEditable(false);
        JTVisor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTVisor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        JTVisor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTVisorKeyPressed(evt);
            }
        });

        JBBac.setText("Bac");
        JBBac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBacActionPerformed(evt);
            }
        });

        JB7.setText("7");
        JB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB7ActionPerformed(evt);
            }
        });

        JB4.setText("4");
        JB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB4ActionPerformed(evt);
            }
        });

        JB1.setText("1");
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });

        JB0.setText("0");
        JB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB0ActionPerformed(evt);
            }
        });

        JBCe.setText("CE");
        JBCe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCeActionPerformed(evt);
            }
        });

        JBCtr.setText("C");
        JBCtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCtrActionPerformed(evt);
            }
        });

        JBMaisMenos.setText("+-");
        JBMaisMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMaisMenosActionPerformed(evt);
            }
        });

        JBDivisao.setText("/");
        JBDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBDivisaoActionPerformed(evt);
            }
        });

        JBVeses.setText("*");
        JBVeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVesesActionPerformed(evt);
            }
        });

        JBMenos.setText("-");
        JBMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMenosActionPerformed(evt);
            }
        });

        JBSoma.setText("+");
        JBSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSomaActionPerformed(evt);
            }
        });

        JBIgual.setText("=");
        JBIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBIgualActionPerformed(evt);
            }
        });

        JB3.setText("3");
        JB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB3ActionPerformed(evt);
            }
        });

        JB6.setText("6");
        JB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB6ActionPerformed(evt);
            }
        });

        JB9.setText("9");
        JB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB9ActionPerformed(evt);
            }
        });

        JB8.setText("8");
        JB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB8ActionPerformed(evt);
            }
        });

        JB5.setText("5");
        JB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB5ActionPerformed(evt);
            }
        });

        JB2.setText("2");
        JB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB2ActionPerformed(evt);
            }
        });

        JBPonto.setText(".");
        JBPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTVisor)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(JB7, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JB8, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JB9, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(JB4, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JB5, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JB6, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(JB0, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBPonto, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBIgual, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(JB1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JB2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JB3, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBDivisao, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(JBMenos, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(JBSoma, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(JBVeses, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JBBac, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBCe, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBCtr, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBMaisMenos, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBBac)
                    .addComponent(JBCe)
                    .addComponent(JBCtr)
                    .addComponent(JBMaisMenos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB7)
                    .addComponent(JB8)
                    .addComponent(JB9)
                    .addComponent(JBDivisao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB4)
                    .addComponent(JB5)
                    .addComponent(JB6)
                    .addComponent(JBVeses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB1)
                    .addComponent(JB2)
                    .addComponent(JB3)
                    .addComponent(JBMenos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB0)
                    .addComponent(JBPonto)
                    .addComponent(JBIgual)
                    .addComponent(JBSoma))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setMnemonic('C');
        jMenu1.setText("Calculadora");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setMnemonic('s');
        jMenuItem1.setText("Fechar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('e');
        jMenu2.setText("Editar");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setMnemonic('C');
        jMenuItem2.setText("Copiar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setMnemonic('o');
        jMenuItem3.setText("Colar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setMnemonic('o');
        jMenu3.setText("Sobre");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB0ActionPerformed
        numeroDigitado("0");
    }

    private void numeroDigitado(String numero) {
        temp = JTVisor.getText();
        numeroant = temp;
        temp = temp + numero;
        JTVisor.setText(temp);
    }//GEN-LAST:event_JB0ActionPerformed

    private void JB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB2ActionPerformed
        numeroDigitado("2");
    }//GEN-LAST:event_JB2ActionPerformed

    private void JB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB6ActionPerformed
        numeroDigitado("6");
    }//GEN-LAST:event_JB6ActionPerformed

    private void JBVesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVesesActionPerformed
        escolheOperacao('*');
    }//GEN-LAST:event_JBVesesActionPerformed

    private void JBPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPontoActionPerformed
        numeroDigitado(".");
    }//GEN-LAST:event_JBPontoActionPerformed

    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
        numeroDigitado("1");
    }//GEN-LAST:event_JB1ActionPerformed

    private void JB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB3ActionPerformed
        numeroDigitado("3");
    }//GEN-LAST:event_JB3ActionPerformed

    private void JB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB4ActionPerformed
        numeroDigitado("4");
    }//GEN-LAST:event_JB4ActionPerformed

    private void JB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB5ActionPerformed
        numeroDigitado("5");
    }//GEN-LAST:event_JB5ActionPerformed

    private void JB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB7ActionPerformed
        numeroDigitado("7");
    }//GEN-LAST:event_JB7ActionPerformed

    private void JB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB8ActionPerformed
        numeroDigitado("8");
    }//GEN-LAST:event_JB8ActionPerformed

    private void JB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB9ActionPerformed
        numeroDigitado("9");
    }//GEN-LAST:event_JB9ActionPerformed

    private void JBSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSomaActionPerformed
        escolheOperacao('+');
    }//GEN-LAST:event_JBSomaActionPerformed

    private void JBIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBIgualActionPerformed
        num2 = Double.valueOf(JTVisor.getText());
        switch (aoperacao) {
            case '+':
                resultado = num1 + num2;
                JTVisor.setText(String.valueOf(resultado));
                break;
            case '-':
                resultado = num1 - num2;
                JTVisor.setText(String.valueOf(resultado));
                break;
            case '*':
                resultado = num1 * num2;
                JTVisor.setText(String.valueOf(resultado));
                break;
            case '/':
                if (num2 == 0) {
                    JTVisor.setText("Impossível dividir por 0.");
                } else {
                    resultado = num1 / num2;
                    JTVisor.setText(String.valueOf(resultado));
                }
                break;
        }
    }//GEN-LAST:event_JBIgualActionPerformed

    private void JBMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMenosActionPerformed
        escolheOperacao('-');
    }//GEN-LAST:event_JBMenosActionPerformed

    private void JBDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBDivisaoActionPerformed
        escolheOperacao('/');
    }//GEN-LAST:event_JBDivisaoActionPerformed

    private void JBCeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCeActionPerformed
        num2 = 0;
        JTVisor.setText(String.valueOf(num1));
    }//GEN-LAST:event_JBCeActionPerformed

    private void JBCtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCtrActionPerformed
        num1 = 0;
        num2 = 0;
        JTVisor.setText("");
    }//GEN-LAST:event_JBCtrActionPerformed

    private void JBBacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBacActionPerformed
        temp = numeroant;
        JTVisor.setText(temp);
        if (numeroant.length() > 1) {
            numeroant = numeroant.substring(0, numeroant.length() - 1);
        } else {
            numeroant = "";
        }
    }//GEN-LAST:event_JBBacActionPerformed

    private void JBMaisMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMaisMenosActionPerformed
        if (temp.startsWith("-")) {
            temp.replace("-", "+");
        } else if (temp.startsWith("+")) {
            temp.replace("+", "-");
        } else {
            temp = "-" + temp;
        }
        JTVisor.setText(temp);
    }//GEN-LAST:event_JBMaisMenosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        copia = JTVisor.getText();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JTVisor.setText(copia);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void JTVisorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTVisorKeyPressed
        chamaBotao(evt);
    }//GEN-LAST:event_JTVisorKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB0;
    private javax.swing.JButton JB1;
    private javax.swing.JButton JB2;
    private javax.swing.JButton JB3;
    private javax.swing.JButton JB4;
    private javax.swing.JButton JB5;
    private javax.swing.JButton JB6;
    private javax.swing.JButton JB7;
    private javax.swing.JButton JB8;
    private javax.swing.JButton JB9;
    private javax.swing.JButton JBBac;
    private javax.swing.JButton JBCe;
    private javax.swing.JButton JBCtr;
    private javax.swing.JButton JBDivisao;
    private javax.swing.JButton JBIgual;
    private javax.swing.JButton JBMaisMenos;
    private javax.swing.JButton JBMenos;
    private javax.swing.JButton JBPonto;
    private javax.swing.JButton JBSoma;
    private javax.swing.JButton JBVeses;
    private javax.swing.JTextField JTVisor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void chamaBotao(KeyEvent evt) {
        switch (evt.getKeyCode()) {
            case 96:
                JB0.doClick();
                break;
            case 97:
                JB1.doClick();
                break;
            case 98:
                JB2.doClick();
                break;
            case 99:
                JB3.doClick();
                break;
            case 100:
                JB4.doClick();
                break;
            case 101:
                JB5.doClick();
                break;
            case 102:
                JB6.doClick();
                break;
            case 103:
                JB7.doClick();
                break;
            case 104:
                JB8.doClick();
                break;
            case 105:
                JB9.doClick();
                break;
            case 48:
                JB0.doClick();
                break;
            case 49:
                JB1.doClick();
                break;
            case 50:
                JB2.doClick();
                break;
            case 51:
                JB3.doClick();
                break;
            case 52:
                JB4.doClick();
                break;
            case 53:
                JB5.doClick();
                break;
            case 54:
                JB6.doClick();
                break;
            case 55:
                JB7.doClick();
                break;
            case 56:
                JB8.doClick();
                break;
            case 57:
                JB9.doClick();
                break;
            case 107:
                JBSoma.doClick();
                break;
            case 109:
                JBMenos.doClick();
                break;
            case 106:
                JBVeses.doClick();
                break;
            case 111:
                JBDivisao.doClick();
                break;
            case 10:
                JBIgual.doClick();
                break;
            case 0:
                JBPonto.doClick();
                break;
            case 46:
                JBPonto.doClick();
                break;
            case 8:
                JBBac.doClick();
                break;
        }
    }
}
