package br.sql.acesso;

import br.sql.acesso.ini.IniFiles;
import javax.swing.JOptionPane;

/**
 *
 * @author Juliano Alves Medina
 */
public class CadastroEmpJanela extends javax.swing.JFrame {

    private boolean fechar = true;

    public boolean isFechar() {
        return fechar;
    }

    public void setFechar(boolean fechar) {
        this.fechar = fechar;
    }

    /**
     * Creates new form CadastroEmpJanela
     */
    public CadastroEmpJanela() {
        initComponents();
    }

    /**
     * Grava no arquivo .ini os dados da conexao com o banco de dados
     */
    public void setIni() {
        IniFiles ini = new IniFiles("Jsys.ini");
        if (nomeLojaTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Obrigatório preencher o campo NOME!");
        } else {
            String N[];
            int x = 0;
            if (ini.getString("LISTA BASE", "LISTA") == null) {
                ini.setString("LISTA BASE", "LISTA", nomeLojaTF.getText().toUpperCase());
            } else {
                if (ini.getString("LISTA BASE", "LISTA") != null) {
                    N = ini.getString("LISTA BASE", "LISTA").split(",");
                    for (String n : N) {
                        if (n.equals(nomeLojaTF.getText().toUpperCase())) {
                            x++;
                        }
                    }
                }
                if (x == 0) {
                    ini.setString("LISTA BASE", "LISTA", new StringBuilder()
                            .append(ini.getString("LISTA BASE", "LISTA"))
                            .append(",")
                            .append(nomeLojaTF.getText().toUpperCase()).toString());
                }
            }
            ini.setString("BASE " + nomeLojaTF.getText().toUpperCase(), "NOMESQLSERVER", nomeLojaTF.getText().toUpperCase());
            ini.setString("BASE " + nomeLojaTF.getText().toUpperCase(), "NOMEDRIVERSQLSERVER", nomeDriverSqlServerCB.getSelectedItem().toString());
            ini.setString("BASE " + nomeLojaTF.getText().toUpperCase(), "HOSTSQLSERVER", HostSqlServerTF.getText().toUpperCase());
            ini.setString("BASE " + nomeLojaTF.getText().toUpperCase(), "PORTASQLSERVER", portaSqlServerTF.getText());
            ini.setString("BASE " + nomeLojaTF.getText().toUpperCase(), "BANCO DE DADOSSQLSERVER", bancoDadosSqlServerTF.getText().toLowerCase());
            ini.setString("BASE " + nomeLojaTF.getText().toUpperCase(), "USUARIOSQLSERVER", usuarioSqlServerTF.getText());
            ini.setString("BASE " + nomeLojaTF.getText().toUpperCase(), "SENHASQLSERVER", String.valueOf(senhaSqlServerPF.getPassword()));
        }
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        nomeDriverSqlServerCB = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        HostSqlServerTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        portaSqlServerTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        bancoDadosSqlServerTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        usuarioSqlServerTF = new javax.swing.JTextField();
        senhaSqlServerPF = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        nomeLojaTF = new javax.swing.JTextField();
        confirma = new javax.swing.JButton();
        cancela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("br/sql/acesso/Bundle"); // NOI18N
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("CadastroEmpJanela.jPanel2.border.title"))); // NOI18N

        jLabel9.setText(bundle.getString("CadastroEmpJanela.jLabel9.text")); // NOI18N

        nomeDriverSqlServerCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "jdbc:sqlserver:" }));

        jLabel10.setText(bundle.getString("CadastroEmpJanela.jLabel10.text")); // NOI18N

        HostSqlServerTF.setText(bundle.getString("CadastroEmpJanela.HostSqlServerTF.text")); // NOI18N

        jLabel11.setText(bundle.getString("CadastroEmpJanela.jLabel11.text")); // NOI18N

        portaSqlServerTF.setText(bundle.getString("CadastroEmpJanela.portaSqlServerTF.text")); // NOI18N

        jLabel12.setText(bundle.getString("CadastroEmpJanela.jLabel12.text")); // NOI18N

        bancoDadosSqlServerTF.setDocument(new br.sql.plainDocument.UppercaseDocument());

        jLabel13.setText(bundle.getString("CadastroEmpJanela.jLabel13.text")); // NOI18N

        jLabel14.setText(bundle.getString("CadastroEmpJanela.jLabel14.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuarioSqlServerTF, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(jLabel13))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senhaSqlServerPF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addComponent(bancoDadosSqlServerTF)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(HostSqlServerTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(portaSqlServerTF, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(nomeDriverSqlServerCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeDriverSqlServerCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HostSqlServerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(portaSqlServerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bancoDadosSqlServerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuarioSqlServerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(senhaSqlServerPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText(bundle.getString("CadastroEmpJanela.jLabel1.text")); // NOI18N

        nomeLojaTF.setDocument(new br.sql.plainDocument.UppercaseDocument());

        confirma.setText(bundle.getString("CadastroEmpJanela.confirma.text")); // NOI18N
        confirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaActionPerformed(evt);
            }
        });

        cancela.setText(bundle.getString("CadastroEmpJanela.cancela.text")); // NOI18N
        cancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(nomeLojaTF)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(confirma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancela)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeLojaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirma)
                    .addComponent(cancela))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaActionPerformed
        setIni();
    }//GEN-LAST:event_confirmaActionPerformed

    private void cancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelaActionPerformed

    /**
     * @param args nao e usado para nada aqui
     */
    public static void main(final String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                CadastroEmpJanela frame = new CadastroEmpJanela();
                frame.pack();
                frame.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HostSqlServerTF;
    private javax.swing.JTextField bancoDadosSqlServerTF;
    private javax.swing.JButton cancela;
    private javax.swing.JButton confirma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox nomeDriverSqlServerCB;
    private javax.swing.JTextField nomeLojaTF;
    private javax.swing.JTextField portaSqlServerTF;
    private javax.swing.JPasswordField senhaSqlServerPF;
    private javax.swing.JTextField usuarioSqlServerTF;
    // End of variables declaration//GEN-END:variables
}
