/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.sql.janelas.financeiro;

import br.JavaApplicationJsys;
import br.sql.acesso.ConnectionFactory;
import br.sql.bean.JsysClientes;
import br.sql.bean.JsysLojas;
import br.sql.bean.JsysSubConta;
import br.sql.bean.JsysTitulos;
import br.sql.bean.Pagamentos;
import br.sql.buscas.ConsultaSubContas;
import br.sql.log.Log;
import br.sql.util.ManagerData;
import br.sql.util.ManagerDecimal;
import br.sql.util.ManagerString;
import br.sql.util.Retorna;
import br.sql.util.Validar;
import java.awt.HeadlessException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Date;
import javax.swing.JOptionPane;
import jsys.sql.Menu;

/**
 *
 * @author Juliano Alves Medina
 */
public class CadastrarParcelamento extends javax.swing.JDialog {

    /**
     * Creates new form CadastrarParcelamento
     *
     * @param parent
     * @param modal
     */
    public CadastrarParcelamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            for (JsysLojas loja : Retorna.jsysLojas()) {
                uJComboBoxEmpresa.addItem(loja.getCnpj() + " - " + loja.getNomeLoja(), loja);
            }
        } catch (Exception e) {
            Log.registraErro(this.getClass().getName(), "caregarDados", e);
            uJComboBoxEmpresa.setSelectedItem("Não Tem Empresas Cadastradas ...");
        }
        // carega retistros dos titulos
        try {
            for (Object O : Retorna.findList("JsysTitulos.findAll")) {
                JsysTitulos t = (JsysTitulos) O;
                uJComboBoxTitulos.addItem(t.getIdTitulo(), t);
            }
            uJComboBoxTitulos.setSelectedIndex(0);
        } catch (Exception ignore) {
            JOptionPane.showMessageDialog(null, "Não Foi Encontrado Títulos Cadastrados!!!");
            this.dispose();
        }
        // carega subConta 
        try {
            for (Object O : Retorna.findList("JsysSubConta.findAll")) {
                JsysSubConta sc = (JsysSubConta) O;
                uJComboBoxTipoPagamentos.addItem(sc.getDescricao() + " - " + sc.getIdGeral(), sc);
            }
        } catch (Exception ignore) {
        }
        // carega retistros dos Corentistas
        try {
            for (Object O : Retorna.findList("JsysClientes.findAllAtivos")) {
                JsysClientes c = (JsysClientes) O;
                uJComboBoxCorentista.addItem(c.getNomeCorentista() + " - " + c.getIdCliente().toString(), c);
            }
            uJComboBoxCorentista.setSelectedIndex(0);
        } catch (Exception ignore) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        uJComboBoxCorentista = new componentes.UJComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        valorTotalTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        valorParcelaTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        uJComboBoxTipoPagamentos = new componentes.UJComboBox();
        jLabel7 = new javax.swing.JLabel();
        uJComboBoxTitulos = new componentes.UJComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        parcelasTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        diasdiscrimiiTF = new javax.swing.JTextField();
        vencimentoFixoCB = new javax.swing.JCheckBox();
        primeiroVencimentoDC = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        diasCB = new componentes.UJComboBox();
        uJComboBoxEmpresa = new componentes.UJComboBox();
        jLabel10 = new javax.swing.JLabel();
        outrosNumerosTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        obsTF = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Parcelamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        uJComboBoxCorentista.setAutocompletar(true);

        jLabel2.setText("Fornecedor");

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Valor Total");

        valorTotalTF.setDocument(new br.sql.plainDocument.MoedaDocument(16));
        valorTotalTF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valorTotalTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valorTotalTFKeyReleased(evt);
            }
        });

        jLabel5.setText("Valor da Parcela");

        valorParcelaTF.setDocument(new br.sql.plainDocument.MoedaDocument(16));
        valorParcelaTF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valorParcelaTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valorParcelaTFKeyReleased(evt);
            }
        });

        jLabel6.setText("Tipo de Pagamento");
        jLabel6.setToolTipText("");

        uJComboBoxTipoPagamentos.setAutocompletar(true);

        jLabel7.setText("Título");

        uJComboBoxTitulos.setAutocompletar(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Vencimento"));

        jLabel4.setText("Parcelas");

        parcelasTF.setDocument(new br.sql.plainDocument.IntegerDocument(5));
        parcelasTF.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        parcelasTF.setText("1");
        parcelasTF.setToolTipText("");
        parcelasTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                parcelasTFKeyReleased(evt);
            }
        });

        jLabel8.setText("Dias");
        jLabel8.setToolTipText("");

        diasdiscrimiiTF.setEditable(false);
        diasdiscrimiiTF.setBackground(new java.awt.Color(255, 255, 102));
        diasdiscrimiiTF.setToolTipText("");

        vencimentoFixoCB.setText("Vencimento Fixo");
        vencimentoFixoCB.setToolTipText("");

        primeiroVencimentoDC.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Primeiro Vencimento");
        jLabel9.setToolTipText("");

        diasCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120", "121", "122", "123", "124", "125", "126", "127", "128", "129", "130", "131", "132", "133", "134", "135", "136", "137", "138", "139", "140", "141", "142", "143", "144", "145", "146", "147", "148", "149", "150", "151", "152", "153", "154", "155", "156", "157", "158", "159", "160", "161", "162", "163", "164", "165", "166", "167", "168", "169", "170", "171", "172", "173", "174", "175", "176", "177", "178", "179", "180", "181", "182", "183", "184", "185", "186", "187", "188", "189", "190", "191", "192", "193", "194", "195", "196", "197", "198", "199", "200", " " }));
        diasCB.setSelectedItem(0);
        diasCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                diasCBItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parcelasTF, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(diasCB, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(diasdiscrimiiTF))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(primeiroVencimentoDC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(vencimentoFixoCB)))
                        .addGap(0, 298, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(diasdiscrimiiTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(parcelasTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diasCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(primeiroVencimentoDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vencimentoFixoCB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        uJComboBoxEmpresa.setAutocompletar(true);

        jLabel10.setText("Empresa");
        jLabel10.setToolTipText("");

        jLabel11.setText("Outros Numeros");

        jLabel12.setText("Obs");

        obsTF.setToolTipText("Adicione uma observação no parcelamento");

        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uJComboBoxCorentista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(obsTF)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(uJComboBoxTipoPagamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uJComboBoxEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(outrosNumerosTF, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valorTotalTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uJComboBoxTitulos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valorParcelaTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(uJComboBoxCorentista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uJComboBoxTipoPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uJComboBoxEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outrosNumerosTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uJComboBoxTitulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorTotalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorParcelaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(obsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void parcelasTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_parcelasTFKeyReleased
        mostraDias();
        setValorParcela();
    }//GEN-LAST:event_parcelasTFKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            for (int i = 0; i < getParcelas(); i++) {
                Pagamentos Registro = new Pagamentos();
                int parcela = i + 1;
                Registro.setOutrosNumeros(outrosNumerosTF.getText() + "/" + parcela);
                Registro.setIdLoja(((JsysLojas) uJComboBoxEmpresa.getSelectedObject()).getIdloja());
                Registro.setIdTitulo(uJComboBoxTitulos.getSelectedItem().toString());
                Date vencimento = getVencimento(i);
                Registro.setDataVencimento(vencimento);
                Registro.setDataUltimoPgto(vencimento);
                Registro.setSemCadastrado(false);
                Registro.setIdBanco(0);
                Registro.setNomeFornecedor(((JsysClientes) uJComboBoxCorentista.getSelectedObject()).getNomeCorentista());
                Registro.setIdFornecedor((JsysClientes) uJComboBoxCorentista.getSelectedObject());
                Registro.setIdContabil(((JsysSubConta) uJComboBoxTipoPagamentos.getSelectedObject()).getIdGeral());
                Registro.setValorTitulo(ManagerDecimal.StringToBigDecimal(valorParcelaTF.getText()));
                Registro.setRestante(ManagerDecimal.StringToBigDecimal(valorParcelaTF.getText()));
                Registro.setMulta(BigDecimal.ZERO);
                Registro.setJuros(BigDecimal.ZERO);
                Registro.setCorrecao(BigDecimal.ZERO);
                Registro.setObs(obsTF.getText());
                if (Registro.getIdPagamentos() == null) {
                    Registro.setUsuarioInclusao(Menu.getNomeUsuario());
                    Registro.setDataEmissao(ManagerData.getDataAtualTypeDate(ManagerData.INICIO));
                    Registro.setDataInclusao(ManagerData.getDataAtualTypeDate(ManagerData.INICIO));
                    ConnectionFactory.insert(Registro);
                } else {
                    Registro.setUsuarioAlteracao(Menu.getNomeUsuario());
                    Registro.setDataAlteracao(ManagerData.getDate());
                    ConnectionFactory.update(Registro);
                }
            }
            JOptionPane.showMessageDialog(this, "Parcelamento criado com sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Erro ou tentar criar o Parcelamento!", "Erro", JOptionPane.ERROR_MESSAGE);
            Log.registraErro(this.getClass().getName(), "criaParcelamento", e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void valorTotalTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorTotalTFKeyReleased
        setValorParcela();
    }//GEN-LAST:event_valorTotalTFKeyReleased

    private void valorParcelaTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorParcelaTFKeyReleased
        try {
            BigDecimal valorParcela = ManagerDecimal.StringToBigDecimal(valorParcelaTF.getText());
            valorTotalTF.setText(ManagerDecimal.converter(valorParcela.multiply(new BigDecimal(getParcelas())).setScale(JavaApplicationJsys.CASA_DECIMAL_VALOR_DEFALT, RoundingMode.HALF_UP), "#,##0.00"));
        } catch (NumberFormatException e) {
            Log.registraErro(this.getClass().getName(), "setValorTotal", e);
        }
    }//GEN-LAST:event_valorParcelaTFKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        br.sql.buscas.ConsultaSubContas consulta = new ConsultaSubContas(new javax.swing.JFrame(), true, new String[]{});
        consulta.setVisible(true);
        if (consulta.isConfirma()) {
            JsysSubConta conta = consulta.getRegistroAtual();
            uJComboBoxTipoPagamentos.setSelectedItem(conta.getDescricao() + " - " + conta.getIdGeral());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void diasCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_diasCBItemStateChanged
        mostraDias();
        setValorParcela();
    }//GEN-LAST:event_diasCBItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.UJComboBox diasCB;
    private javax.swing.JTextField diasdiscrimiiTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField obsTF;
    private javax.swing.JTextField outrosNumerosTF;
    private javax.swing.JTextField parcelasTF;
    private com.toedter.calendar.JDateChooser primeiroVencimentoDC;
    private componentes.UJComboBox uJComboBoxCorentista;
    private componentes.UJComboBox uJComboBoxEmpresa;
    private componentes.UJComboBox uJComboBoxTipoPagamentos;
    private componentes.UJComboBox uJComboBoxTitulos;
    private javax.swing.JTextField valorParcelaTF;
    private javax.swing.JTextField valorTotalTF;
    private javax.swing.JCheckBox vencimentoFixoCB;
    // End of variables declaration//GEN-END:variables

    private void mostraDias() {
        try {
            BigDecimal dias = getDias();
            if (!vencimentoFixoCB.isSelected() & getParcelas() != 0) {
                StringBuilder valor = new StringBuilder(dias.toString());
                BigDecimal somaDias = dias;
                somaDias.setScale(0);
                for (int i = 1; i < getParcelas(); i++) {
                    somaDias = somaDias.add(dias);
                    valor.append("/").append(somaDias);
                }
                diasdiscrimiiTF.setText(valor.toString());
            }
        } catch (NumberFormatException e) {
            Log.registraErro(this.getClass().getName(), "mostraDias", e);
        }
    }

    private Integer getParcelas() {
        Integer parcelas = 0;
        if (!parcelasTF.getText().equals("")) {
            parcelas = Integer.valueOf(parcelasTF.getText());
        }
        return parcelas;
    }

    private BigDecimal getDias() {
        return ManagerDecimal.StringToBigDecimal(String.valueOf(diasCB.getSelectedItem())).setScale(0);
    }

    private Date getVencimento(Integer i) {
        if (i == 0) {
            return primeiroVencimentoDC.getDate();
        } else if (vencimentoFixoCB.isSelected()) {
            Date venc = primeiroVencimentoDC.getDate();
            return ManagerData.getDate(venc, 0, i, 0);
        } else {
            BigDecimal dias = getDias();
            BigDecimal parcela = new BigDecimal(i);
            return ManagerData.sumDays(primeiroVencimentoDC.getDate(), parcela.multiply(dias).intValue());
        }
    }

    private void setValorParcela() {
        try {
            if (getParcelas() > 0 ) {
                String sTotal = ManagerString.noNull(valorTotalTF.getText(), "0");
                BigDecimal valorTotal = ManagerDecimal.StringToBigDecimal(sTotal);
                valorParcelaTF.setText(ManagerDecimal.converter(valorTotal.divide(new BigDecimal(getParcelas()), 2, RoundingMode.HALF_UP), "#,##0.00"));
            }
        } catch (NumberFormatException e) {
            Log.registraErro(this.getClass().getName(), "setValorParcela", e);
        }
    }
}
