package br.sql.janelas.financeiro;

import br.sql.acesso.ConnectionFactory;
import br.sql.bean.JsysBancos;
import br.sql.bean.JsysCheques;
import br.sql.bean.JsysClientes;
import br.sql.bean.JsysLojas;
import br.sql.bean.JsysParametros;
import br.sql.util.ManagerData;
import br.sql.util.ManagerDecimal;
import br.sql.util.Retorna;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import jsys.sql.Menu;

/**
 *
 * @author Juliano Alves Medina
 */
public class ChequesEdit extends javax.swing.JDialog {

    private final JsysCheques cheque;
    private final JsysParametros par = Retorna.JsysParametros();

    /**
     * Creates new form chequesEdit
     *
     * @param parent
     * @param modal
     * @param cheque
     */
    public ChequesEdit(java.awt.Frame parent, boolean modal, JsysCheques cheque) {
        super(parent, modal);
        this.cheque = cheque;
        this.cheque.setDataEmissao(ManagerData.getDataAtualTypeDate(ManagerData.INICIO));
        this.cheque.setDataInclusao(ManagerData.getDate());
        this.cheque.setUsuarioInclusao(Menu.getNomeUsuario());
        initComponents();
        caregaDados();
    }

    public ChequesEdit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.cheque = new JsysCheques();
        this.cheque.setDataEmissao(ManagerData.getDataAtualTypeDate(ManagerData.INICIO));
        initComponents();
        caregaDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelcodigo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBoxEmitido = new javax.swing.JCheckBox();
        uJComboBoxBancos = new componentes.UJComboBox();
        jLabel3 = new javax.swing.JLabel();
        jDateChooserEmissao = new com.toedter.calendar.JDateChooser();
        jDateChooserVencimento = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        uJComboBoxCliente = new componentes.UJComboBox();
        jCheckBoxSemCadastro = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNumeroCheque = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldOutrosNumeros = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObs = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        uJComboBoxLojas = new componentes.UJComboBox();
        cancelarJbuton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextFieldNomeCorentista = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jTextField20 = new javax.swing.JTextField();
        jTextFieldUsuarioInclusao = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jTextField25 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jCheckBoxDevolvido = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cheques");
        jLabel1.setToolTipText("");

        jLabelcodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelcodigo.setText("0");
        jLabelcodigo.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelcodigo)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabelcodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setText("Banco");
        jLabel2.setToolTipText("");

        jCheckBoxEmitido.setSelected(true);
        jCheckBoxEmitido.setText("Emitido");
        jCheckBoxEmitido.setToolTipText("");

        uJComboBoxBancos.setAutocompletar(true);

        jLabel3.setText("Emissao");

        jLabel4.setText("Pré-datado");
        jLabel4.setToolTipText("");

        jLabel5.setText("Cedente");
        jLabel5.setToolTipText("");

        uJComboBoxCliente.setAutocompletar(true);

        jCheckBoxSemCadastro.setText("Sem Cadastro");
        jCheckBoxSemCadastro.setToolTipText("");
        jCheckBoxSemCadastro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxSemCadastroStateChanged(evt);
            }
        });

        jLabel6.setText("Valor");
        jLabel6.setToolTipText("");

        jTextFieldValor.setDocument(new br.sql.plainDocument.MoedaDocument(16)
        );
        jTextFieldValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldValor.setToolTipText("");

        jLabel7.setText("Numero do Cheque");
        jLabel7.setToolTipText("");

        jLabel8.setText("Outros Numeros");
        jLabel8.setToolTipText("");

        jLabel9.setText("Obs");

        jTextAreaObs.setColumns(20);
        jTextAreaObs.setRows(5);
        jScrollPane1.setViewportView(jTextAreaObs);

        jLabel10.setText("Loja");
        jLabel10.setToolTipText("");

        uJComboBoxLojas.setAutocompletar(true);

        cancelarJbuton.setText("Cancelar");
        cancelarJbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarJbutonActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 0));
        jButton2.setText("Confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextFieldNomeCorentista.setToolTipText("");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario Inclusão"));

        jTextField20.setEditable(false);
        jTextField20.setBackground(new java.awt.Color(204, 255, 204));
        jTextField20.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jTextField20.setText(br.sql.util.ManagerData.convertDate(cheque.getDataInclusao(), "dd/MM/yyyy HH:mm:ss")
        );

        jTextFieldUsuarioInclusao.setEditable(false);
        jTextFieldUsuarioInclusao.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldUsuarioInclusao.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jTextFieldUsuarioInclusao.setText(cheque.getUsuarioInclusao());

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUsuarioInclusao, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextFieldUsuarioInclusao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario Alteração"));

        jTextField25.setEditable(false);
        jTextField25.setBackground(new java.awt.Color(204, 255, 204));
        jTextField25.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jTextField25.setText(cheque.getUsuarioAlteracao());

        jTextField21.setEditable(false);
        jTextField21.setBackground(new java.awt.Color(204, 255, 204));
        jTextField21.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jTextField21.setText(br.sql.util.ManagerData.convertDate(cheque.getDataAlteracao(), "dd/MM/yyyy HH:mm:ss"));
        jTextField21.setToolTipText("");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jCheckBoxDevolvido.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBoxDevolvido.setText("Devolvido");
        jCheckBoxDevolvido.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(uJComboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldNomeCorentista, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxSemCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(uJComboBoxBancos, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxEmitido)
                                .addGap(91, 91, 91))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(102, 102, 102)
                                .addComponent(jLabel4))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jDateChooserEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jDateChooserVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(6, 6, 6)
                        .addComponent(cancelarJbuton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jTextFieldNumeroCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldOutrosNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(uJComboBoxLojas, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(81, 81, 81)
                                        .addComponent(jLabel8)
                                        .addGap(105, 105, 105)
                                        .addComponent(jLabel10)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBoxDevolvido)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uJComboBoxBancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxEmitido)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(uJComboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBoxSemCadastro))
                            .addComponent(jTextFieldNomeCorentista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNumeroCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldOutrosNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uJComboBoxLojas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxDevolvido))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2)
                        .addComponent(cancelarJbuton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxSemCadastroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxSemCadastroStateChanged
        if (jCheckBoxSemCadastro.isSelected()) {
            uJComboBoxCliente.setVisible(false);
            jTextFieldNomeCorentista.setVisible(true);
            uJComboBoxCliente.setSelectedIndex(0);
        } else {
            uJComboBoxCliente.setVisible(true);
            jTextFieldNomeCorentista.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBoxSemCadastroStateChanged

    private void cancelarJbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarJbutonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarJbutonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (validar()) {
            cheque.setEmitidos(jCheckBoxEmitido.isSelected());
            cheque.setDevolvido(jCheckBoxDevolvido.isSelected());
            cheque.setDataEmissao(ManagerData.setHoraInicioDia(jDateChooserEmissao.getDate()));
            cheque.setDataVencimento(ManagerData.setHoraInicioDia(jDateChooserVencimento.getDate()));
            cheque.setNumeroCheque(jTextFieldNumeroCheque.getText());
            cheque.setOutrosNumeros(jTextFieldOutrosNumeros.getText());
            cheque.setValorCheque(ManagerDecimal.StringToBigDecimal(jTextFieldValor.getText()));
            cheque.setObs(jTextAreaObs.getText());
            cheque.setIdBanco((JsysBancos) uJComboBoxBancos.getSelectedObject());
            cheque.setIdLoja((JsysLojas) uJComboBoxLojas.getSelectedObject());
            cheque.setUsuarioAlteracao(Menu.getNomeUsuario());
            cheque.setDataAlteracao(ManagerData.getDate());
            cheque.setSemCadastrado(jCheckBoxSemCadastro.isSelected());
            if (jCheckBoxSemCadastro.isSelected()) {
                cheque.setIdCliente(Retorna.jsysClientes(par.getIdForncedor()));
                cheque.setNomeCorentista(jTextFieldNomeCorentista.getText());
            } else {
                cheque.setIdCliente((JsysClientes) uJComboBoxCliente.getSelectedObject());
                cheque.setNomeCorentista(((JsysClientes) uJComboBoxCliente.getSelectedObject()).getNomeCorentista());
            }
            if (cheque.getIdcheque() == null) {
                cheque.setDataInclusao(ManagerData.getDate());
                cheque.setUsuarioInclusao(Menu.getNomeUsuario());
                ConnectionFactory.insert(cheque);
            } else {
                cheque.setDataAlteracao(ManagerData.getDate());
                cheque.setUsuarioAlteracao(Menu.getNomeUsuario());
                ConnectionFactory.update(cheque);
            }
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarJbuton;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBoxDevolvido;
    private javax.swing.JCheckBox jCheckBoxEmitido;
    private javax.swing.JCheckBox jCheckBoxSemCadastro;
    private com.toedter.calendar.JDateChooser jDateChooserEmissao;
    private com.toedter.calendar.JDateChooser jDateChooserVencimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelcodigo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaObs;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextFieldNomeCorentista;
    private javax.swing.JTextField jTextFieldNumeroCheque;
    private javax.swing.JTextField jTextFieldOutrosNumeros;
    private javax.swing.JTextField jTextFieldUsuarioInclusao;
    private javax.swing.JTextField jTextFieldValor;
    private componentes.UJComboBox uJComboBoxBancos;
    private componentes.UJComboBox uJComboBoxCliente;
    private componentes.UJComboBox uJComboBoxLojas;
    // End of variables declaration//GEN-END:variables

    private void caregaDados() {
        for (Object O : Retorna.findList("JsysBancos.findAll")) {
            JsysBancos b = (JsysBancos) O;
            uJComboBoxBancos.addItem(b.getNomeBanco() + " Agencia: " + b.getNumeroBanco() + " Conta:" + b.getNumeroConta() + "-" + b.getNumeroBancoDv(), b);
        }
        for (Object O : Retorna.jsysLojas()) {
            JsysLojas l = (JsysLojas) O;
            uJComboBoxLojas.addItem(l.getNomeLoja() + " - " + l.getCnpj(), l);
        }
        for (Object O : Retorna.findList("JsysClientes.findAllAtivos")) {
            JsysClientes c = (JsysClientes) O;
            uJComboBoxCliente.addItem(c.getNomeCorentista() + " - " + c.getIdCliente(), c);
        }
        if (cheque != null) {
            jLabelcodigo.setText(cheque.getIdcheque() == null ? "0" : cheque.getIdcheque().toString());
            jCheckBoxEmitido.setSelected(cheque.getEmitidos());
            jCheckBoxDevolvido.setSelected(cheque.isDevolvido());
            jDateChooserEmissao.setDate(cheque.getDataEmissao());
            jDateChooserVencimento.setDate(cheque.getDataVencimento());
            jCheckBoxSemCadastro.setSelected(cheque.getSemCadastrado());
            jTextFieldNumeroCheque.setText(cheque.getNumeroCheque());
            jTextFieldOutrosNumeros.setText(cheque.getOutrosNumeros());
            jTextFieldValor.setText(ManagerDecimal.converter(cheque.getValorCheque(), "#,##0.00"));
            jTextAreaObs.setText(cheque.getObs());
            jTextFieldNomeCorentista.setText(cheque.getNomeCorentista());
            if (cheque.getIdCliente() != null) {
                uJComboBoxCliente.setSelectedItem(cheque.getIdCliente().getNomeCorentista() + " - " + cheque.getIdCliente().getIdCliente());
            }
            if (cheque.getIdBanco() != null) {
                uJComboBoxBancos.setSelectedItem(cheque.getIdBanco().getNomeBanco()
                        + " Agencia: " + cheque.getIdBanco().getNumeroBanco()
                        + " Conta:" + cheque.getIdBanco().getNumeroConta() + "-" + cheque.getIdBanco().getNumeroBancoDv());
            }
            if (cheque.getIdLoja() != null) {
                uJComboBoxLojas.setSelectedItem(cheque.getIdLoja().getNomeLoja() + " - " + cheque.getIdLoja().getCnpj());
            }
        }
    }

    private boolean validar() {
        if (jDateChooserVencimento.getDate() == null) {
            JOptionPane.showConfirmDialog(this, "Obrigatório preencher o campo Pré-datado!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (ManagerDecimal.StringToBigDecimal(jTextFieldValor.getText()).compareTo(BigDecimal.ZERO) == 0) {
            JOptionPane.showConfirmDialog(this, "O Valor tem que ser maior que zero!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (jTextFieldValor.getText() == null) {
            JOptionPane.showConfirmDialog(this, "Obrigatório preencher o campo Valor!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
}
