package br.sql.janelas.caixa;

import br.sql.acesso.ConnectionFactory;
import br.sql.bean.JsysClientes;
import br.sql.bean.JsysLojas;
import br.sql.bean.JsysParametros;
import br.sql.bean.JsysSubConta;
import br.sql.bean.JsysTitulos;
import br.sql.bean.Pagamentos;
import br.sql.buscas.ConsultaSubContas;
import br.sql.log.Log;
import br.sql.util.ManagerData;
import br.sql.util.ManagerDecimal;
import br.sql.util.ManagerString;
import br.sql.util.ReportUtils;
import br.sql.util.Retorna;
import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import jsys.sql.Menu;

/**
 *
 * @author Juliano Alves Medina
 */
public final class PagamentosCaixa extends javax.swing.JDialog {

    private static final JsysParametros PAR = Retorna.JsysParametros();

    /**
     * Creates new form PagamentosCaixa
     *
     */
    @SuppressWarnings("unchecked")
    public PagamentosCaixa() {
        super(new javax.swing.JFrame(), false);
        setTitle("Pagamento");
        initComponents();
        caregaDados();
        uJComboBoxClientes.requestFocus();
        HashSet conj = new HashSet(jPanel2.getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        jPanel2.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        queryTitulos = java.beans.Beans.isDesignTime() ? null : ConnectionFactory.getEntityManagerNew().createQuery("SELECT j FROM JsysTitulos j WHERE j.ativo = 1 ORDER BY j.idcupom");
        listTitulos = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryTitulos.getResultList());
        querySubConta = java.beans.Beans.isDesignTime() ? null : ConnectionFactory.getEntityManagerNew().createQuery("SELECT j FROM JsysSubConta j ORDER BY j.descricao");
        listSubConta = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(querySubConta.getResultList());
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxTitulos = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObs = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jCheckBoxSemCadastro = new javax.swing.JCheckBox();
        uJComboBoxClientes = new componentes.UJComboBox();
        jTextFieldClienteSemCadastro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        uJComboBoxTipoPagamento = new componentes.UJComboBox();
        uJComboBoxLoja = new componentes.UJComboBox();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagamento");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Pagamento");
        jLabel1.setToolTipText("");

        jLabel2.setText("Data:");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText(ManagerData.convertBrDate(ManagerData.getDate()));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addComponent(jLabel3))
        );

        jComboBoxTitulos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxTitulos.setRenderer(new br.sql.defaultListCellRenderer.Titulos());

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listTitulos, jComboBoxTitulos);
        bindingGroup.addBinding(jComboBoxBinding);

        jTextAreaObs.setColumns(20);
        jTextAreaObs.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextAreaObs.setRows(5);
        jScrollPane1.setViewportView(jTextAreaObs);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Fornecedor / Funcionario");
        jLabel4.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Titulo");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Correspondente a ");
        jLabel10.setToolTipText("");

        jCheckBoxSemCadastro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBoxSemCadastro.setText("Sem Cadastro");
        jCheckBoxSemCadastro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxSemCadastroStateChanged(evt);
            }
        });
        jCheckBoxSemCadastro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCheckBoxSemCadastroPropertyChange(evt);
            }
        });

        uJComboBoxClientes.setAutocompletar(true);
        uJComboBoxClientes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldClienteSemCadastro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Valor");

        jTextFieldValor.setDocument(new br.sql.plainDocument.MoedaDocument(15)
        );
        jTextFieldValor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldValor.setToolTipText("");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tipo Pagamento");

        uJComboBoxTipoPagamento.setAutocompletar(true);
        uJComboBoxTipoPagamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        uJComboBoxLoja.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Empresa");
        jLabel8.setToolTipText("");

        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldClienteSemCadastro)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBoxSemCadastro)
                                .addGap(9, 9, 9))
                            .addComponent(uJComboBoxClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxTitulos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(uJComboBoxLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                                        .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(uJComboBoxTipoPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCheckBoxSemCadastro))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldClienteSemCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uJComboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8))
                    .addComponent(jLabel5))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTitulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uJComboBoxLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uJComboBoxTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(4, 4, 4)
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(11, 11, 11)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Pagamentos p = new Pagamentos();
        p.setOutrosNumeros("");
        p.setDocOrdem("");
        p.setCodEmpresa("");
        p.setIdTitulo(getjComboBoxTitulos().getIdTitulo()); // pegar valor janela 
        if (jCheckBoxSemCadastro.isSelected()) {
            JsysClientes c = Retorna.jsysClientes(PAR.getIdForncedor());
            p.setIdFornecedor(c); // pegar valor janela 
            p.setNomeFornecedor(ManagerString.Left(jTextFieldClienteSemCadastro.getText(), 60)); // pegar valor janela 
        } else {
            p.setIdFornecedor(getuJComboBoxClientes()); // pegar valor janela 
            p.setNomeFornecedor(getuJComboBoxClientes().getNomeCorentista()); // pegar valor janela 
        }
        p.setSemCadastrado(jCheckBoxSemCadastro.isSelected());
        p.setDataEmissao(ManagerData.setHoraInicioDia(ManagerData.getDate()));
        p.setDataVencimento(ManagerData.setHoraInicioDia(ManagerData.getDate()));
        p.setValorTitulo(ManagerDecimal.StringToBigDecimal(jTextFieldValor.getText()));
        p.setValorPago(ManagerDecimal.StringToBigDecimal(jTextFieldValor.getText()));
        p.setRestante(BigDecimal.ZERO);
        p.setValorEstorno(BigDecimal.ZERO);
        p.setIdBanco(Menu.getIdBanco());
        p.setDataPagamento(ManagerData.setHoraInicioDia(ManagerData.getDate()));
        p.setIdContabil(getuJComboBoxTipoPagamento().getIdGeral());
        p.setMulta(BigDecimal.ZERO);
        p.setJuros(BigDecimal.ZERO);
        p.setCorrecao(BigDecimal.ZERO);
        p.setDespesas(BigDecimal.ZERO);
        p.setDescontos(BigDecimal.ZERO);
        p.setDataUltimoPgto(ManagerData.setHoraInicioDia(ManagerData.getDate()));
        p.setDataInclusao(ManagerData.getDate());
        p.setUsuarioInclusao(Menu.getNomeUsuario());
        p.setIdTituloBaixa(getjComboBoxTitulos().getIdTitulo());
        p.setQuitado(true);
        p.setObs(jTextAreaObs.getText());
        p.setIdLoja(getuJComboBoxLoja().getIdloja());
        if (br.sql.acesso.ConnectionFactory.insert(p) instanceof Pagamentos) {
            if (JOptionPane.showOptionDialog(this,
                    "Pagamento Efetuado com Sucesso"
                    + System.lineSeparator()
                    + "Deseja imprimir o Recibo?",
                    "Sucesso",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null, br.JavaApplicationJsys.OPTIONS, br.JavaApplicationJsys.OPTIONS[1]) == 0) {
                Map<Object, Object> parametros = new HashMap<>();
                parametros.put("idPagamento", p.getIdPagamentos());
                ReportUtils.openReport("Recibo de Pagamento ",
                        "/br/rel/caixa/ReciboPagamento.jasper",
                        parametros);
            }
            this.dispose();
        } else {
            Log.registraErro(this.getClass().getName(), "jButton2ActionPerformed", new Exception("erro inesperado"));
            JOptionPane.showMessageDialog(null, "Pagamento Não Efetuado", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBoxSemCadastroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCheckBoxSemCadastroPropertyChange
        trocaTipoCliente();
    }//GEN-LAST:event_jCheckBoxSemCadastroPropertyChange

    private void jCheckBoxSemCadastroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxSemCadastroStateChanged
        trocaTipoCliente();
    }//GEN-LAST:event_jCheckBoxSemCadastroStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ConsultaSubContas consulta = new ConsultaSubContas(new javax.swing.JFrame(), true, new String[]{});
        consulta.setVisible(true);
        if (consulta.isConfirma()) {
            JsysSubConta conta = consulta.getRegistroAtual();
            uJComboBoxTipoPagamento.setSelectedItem(conta.getDescricao() + " - " + conta.getIdGeral());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBoxSemCadastro;
    private javax.swing.JComboBox jComboBoxTitulos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaObs;
    private javax.swing.JTextField jTextFieldClienteSemCadastro;
    private javax.swing.JTextField jTextFieldValor;
    private java.util.List<br.sql.bean.JsysSubConta> listSubConta;
    private java.util.List<br.sql.bean.JsysTitulos> listTitulos;
    private javax.persistence.Query querySubConta;
    private javax.persistence.Query queryTitulos;
    private componentes.UJComboBox uJComboBoxClientes;
    private componentes.UJComboBox uJComboBoxLoja;
    private componentes.UJComboBox uJComboBoxTipoPagamento;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void caregaDados() {
        List<Object> O = Retorna.findList("JsysClientes.findAllAtivos");
        for (Object o : O) {
            JsysClientes c = (JsysClientes) o;
            uJComboBoxClientes.addItem(c.getNomeCorentista(), c);
        }
        for (JsysSubConta s : listSubConta) {
            uJComboBoxTipoPagamento.addItem(s.getDescricao() + " - " + s.getIdGeral(), s);
        }
        for (JsysLojas l : Retorna.jsysLojas()) {
            uJComboBoxLoja.addItem(l.getNomeLoja() + " - " + l.getCnpj(), l);
        }
        Map<Object, Object> filtro = new HashMap<>();
        filtro.put("ativo", true);
        JsysLojas jL = ((JsysLojas) Retorna.findOneResult("JsysLojas.findByAtivo", filtro));
        uJComboBoxLoja.setSelectedItem(jL.getNomeLoja() + " - " + jL.getCnpj());
    }

    /**
     * @return para retornar o objeto utilise o método getSelectedObject para
     * retornar o nome utilize o método getSelectedItem
     */
    private JsysClientes getuJComboBoxClientes() {
        return (JsysClientes) uJComboBoxClientes.getSelectedObject();
    }

    private JsysSubConta getuJComboBoxTipoPagamento() {
        return (JsysSubConta) uJComboBoxTipoPagamento.getSelectedObject();
    }

    /**
     * para retornar o objeto utilise o método getSelectedObject para retornar o
     * nome utilize o método getSelectedItem
     */
    private JsysTitulos getjComboBoxTitulos() {
        return (JsysTitulos) jComboBoxTitulos.getSelectedItem();
    }

    private JsysLojas getuJComboBoxLoja() {
        return (JsysLojas) uJComboBoxLoja.getSelectedObject();
    }

    private void trocaTipoCliente() {
        uJComboBoxClientes.setVisible(!jCheckBoxSemCadastro.isSelected());
        jTextFieldClienteSemCadastro.setVisible(jCheckBoxSemCadastro.isSelected());
    }
}
