package br.sql.janelas.liberacoes;

import br.sql.bean.JsysOrcamento;
import br.sql.bean.JsysOrcamentoItens;
import br.sql.bean.JsysReceber;
import br.sql.defaultTableCellRenderer.ZebradoLocation;
import br.sql.util.ManagerData;
import br.sql.util.ManagerDecimal;
import br.sql.util.Retorna;
import br.sql.util.Validar;
import java.awt.event.WindowEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juliano Alves Medina
 */
public class recebimentoCancelamento extends javax.swing.JDialog {

    private JsysOrcamento jsysOrcamento;
    private Integer seqReceber;

    /**
     * Creates new form recebimentoCancelamento
     *
     * @param parent
     * @param modal
     */
    public recebimentoCancelamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.jsysOrcamento = null;
        initComponents();
        this.addWindowListener(new java.awt.event.WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                dispose(false);
            }
        });
    }

    public void dispose(boolean confirmar) {
        if (!confirmar) {
            this.jsysOrcamento = null;
        }
        super.dispose();
    }

    /**
     * Get the value of RetornoId
     *
     * @return the value of RetornoId
     */
    public Integer getRetornoId() {
        return this.jsysOrcamento == null ? null : this.jsysOrcamento.getIdOrcamento();
    }

    public Integer getSeqReceber() {
        return seqReceber;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idVenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jTextFieldData = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldVendedor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        uJComboBoxSeq = new componentes.UJComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cancelar Recebimento");
        setResizable(false);

        jLabel1.setText("Codigo da venda");
        jLabel1.setToolTipText("");

        idVenda.setDocument(new br.sql.plainDocument.IntegerDocument(10)
        );
        idVenda.setToolTipText("");
        idVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idVendaKeyReleased(evt);
            }
        });

        jLabel2.setText("Valor");
        jLabel2.setToolTipText("");

        jTextFieldValor.setEditable(false);
        jTextFieldValor.setBackground(new java.awt.Color(153, 255, 255));
        jTextFieldValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldValor.setText("R$ 0.00");
        jTextFieldValor.setToolTipText("");

        jTextFieldData.setEditable(false);
        jTextFieldData.setBackground(new java.awt.Color(153, 255, 255));
        jTextFieldData.setToolTipText("");

        jLabel3.setText("Data");
        jLabel3.setToolTipText("");

        jLabel4.setText("Vendedor");
        jLabel4.setToolTipText("");

        jTextFieldVendedor.setEditable(false);
        jTextFieldVendedor.setBackground(new java.awt.Color(153, 255, 255));
        jTextFieldVendedor.setToolTipText("");

        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Jsys Produtos T");
        }

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Confirmar");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Seq");
        jLabel5.setToolTipText("");

        uJComboBoxSeq.setAutocompletar(true);
        uJComboBoxSeq.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                uJComboBoxSeqItemStateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Cancelar Recebimento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uJComboBoxSeq, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValor)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldVendedor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(uJComboBoxSeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    @SuppressWarnings("unchecked")
    private void idVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idVendaKeyReleased
        if (Validar.isNotNullOrWhite(idVenda.getText())) {
            jTextFieldData.setText("");
            jTextFieldVendedor.setText("");
            jTextFieldValor.setText("R$ 0.00");
            uJComboBoxSeq.clear();
            this.seqReceber = null;
            jTable1.removeAll();
            Map<Object, Object> filtro = new HashMap<>();
            filtro.put("idOrcamento", Integer.valueOf(idVenda.getText()));
            this.jsysOrcamento = (JsysOrcamento) Retorna.findOneResult("JsysOrcamento.findByFechado", filtro);
            if (this.jsysOrcamento != null) {
                jTextFieldData.setText(ManagerData.convertDate(this.jsysOrcamento.getData(), "dd/MM/yyyy"));
                jTextFieldVendedor.setText(this.jsysOrcamento.getIdFuncionario().getIdCliente() + " - " + this.jsysOrcamento.getIdFuncionario().getNomeCorentista());
                jTextFieldValor.setText(ManagerDecimal.converter(this.jsysOrcamento.getValorLiquido(), "R$ #,##0.00"));
                filtro.clear();
                filtro.put("idReceber", this.jsysOrcamento.getIdOrcamento());
                java.util.Collection collection = Retorna.findCollection("JsysReceber.findByIdReceber", filtro);
                for (Object c : collection) {
                    JsysReceber r = (JsysReceber) c;
                    uJComboBoxSeq.addItem(r.getJsysReceberPK().getSeqReceber());
                }
                uJComboBoxSeq.setSelectedIndex(0);
                this.seqReceber = (Integer) uJComboBoxSeq.getSelectedObject();
                DefaultTableModel aModel = new DefaultTableModel(new Object[][]{}, new String[]{
                    "Codigo",
                    "Descrição",
                    "Quantidade",
                    "Total Produto"}) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                };
                for (JsysOrcamentoItens o : this.jsysOrcamento.getJsysOrcamentoItensCollection()) {
                    Object[] objects = new Object[4];
                    objects[0] = o.getJsysProdutosT().getIdProduto();
                    objects[1] = o.getJsysProdutosT().getNomeProduto();
                    objects[2] = o.getQuantidade();
                    objects[3] = o.getTotalProduto();
                    aModel.addRow(objects);
                }
                jTable1.setModel(aModel);
                jTable1.getColumnModel().getColumn(0).setPreferredWidth(80);
                jTable1.getColumnModel().getColumn(1).setPreferredWidth(258);
                jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
                jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
                jTable1.setDefaultRenderer(Object.class, new ZebradoLocation());
            }
        }
    }//GEN-LAST:event_idVendaKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (this.jsysOrcamento != null & this.seqReceber != null) {
            this.dispose(true);
        } else {
            JOptionPane.showMessageDialog(this, "Orçamento não Encontrado!!!");
            idVenda.requestFocus();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void uJComboBoxSeqItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_uJComboBoxSeqItemStateChanged
        this.seqReceber = (Integer) uJComboBoxSeq.getSelectedObject();
    }//GEN-LAST:event_uJComboBoxSeqItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idVenda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldValor;
    private javax.swing.JTextField jTextFieldVendedor;
    private componentes.UJComboBox uJComboBoxSeq;
    // End of variables declaration//GEN-END:variables
}
